### ISSUE TITLE
Blank songs can be added

### ISSUE THREAD

**Issue by vicwomg** [vicwomg/pikaraoke#1]
Noticed this in a few large group sessions: a blank song gets added to the queue. When trying to delete it from the queue, the current song skips. 

Not sure how this is happening. Perhaps double-submitting to queue, bad chars in the title, etc.

**Comment by vicwomg** [comment]
Pushed a fix for unicode breakage w/ Chinese and other foreign language chars.  That may address this, but will keep open for now. ff066a3b6cb29407e0e5fb96ceb7744af9750f3f

**Comment by petemarvin** [comment]
I had experienced this issue lately.
![image](https://user-images.githubusercontent.com/40055959/90630595-e6c42a80-e253-11ea-9c92-3fad705b16e4.png)
