### ISSUE TITLE
Feature request: Master user / guest user

### ISSUE THREAD

**Issue by iMelsom** [vicwomg/pikaraoke#101]
In addition to the ability now to give a name, I would like to hide the system functions menu so that it is only available to a Master user. Especially since users get access to shutdown or restart the server. 

In the same note It would be nice to be able to hide the player buttons that gives users the ability to skip songs or adust song settings, again only letting the master user do this. This should be a setting to disable or enable access to player buttons. (including key change buttons)

**Comment by vicwomg** [comment]
This feature already exists. Try the --admin-password option to enable administrator mode

**Comment by iMelsom** [comment]
Thanks for your reply. I will try this :)
