### ISSUE TITLE
Bug: capital letters are sorted before non capital letters in the browse view

### ISSUE THREAD

**Issue by iMelsom** [vicwomg/pikaraoke#104]
The stored song list is case sensistive now. It should be case insensitive

**Comment by vicwomg** [comment]
Can you explain this further? I'm not sure I understand the issue.

**Comment by iMelsom** [comment]
In the song list for stored songs, captial letters are sorted before non capital letters. This means all songs or artists starting with a capital letter is listed before any songs or artists not starting with capital letters. See attached image

![image](https://user-images.githubusercontent.com/17039544/107818563-1cb41880-6d78-11eb-8409-c2de34fa33a4.png)

As Capital letters are listed before non capital letters, sorting gets weird if there are capital letters not in the first character.

**Comment by vicwomg** [comment]
Oh my gosh, that's a bug indeed. Updating the title to better match what you're saying

**Comment by jramboz** [comment]
I think I found the problem. It's in `karaoke.py` line 453. Try changing:

`self.available_songs = sorted(files_grabbed)`

to:

`self.available_songs = sorted(files_grabbed, key=str.lower)`

Thanks to [this StackOverflow answer](https://stackoverflow.com/questions/20535495/case-insensitive-sorting-with-sortlist-key-str-lower/20535542)!

**Comment by iMelsom** [comment]
Yep. 
Changing that fixed this for me:)

**Comment by vicwomg** [comment]
this is on development branch, will go out with next release
