### ISSUE TITLE
Duplicate songs

### ISSUE THREAD

**Issue by viperxx01** [vicwomg/pikaraoke#115]
theres a bug in version 1.1.1 they duplicate all songs in library. im using windows. im using 1.1.0 and its no problem

**Comment by vicwomg** [comment]
Thanks for the report. confirmed on windows only, might be related to #108

**Comment by vicwomg** [comment]
Found the issue. This should be fixed in the development branch and will be in the next release.

**Comment by viperxx01** [comment]
thank you so much.

**Comment by jramboz** [comment]
It wasn't my fault (this time)! :D

**Comment by vicwomg** [comment]
@jramboz it most definitely was not your fault 😬 All me  with #95  I should have checked before pointing fingers!

**Comment by viperxx01** [comment]
can i ask one more pls. im not so good with programming

this is api of musixmatch.
from musixmatch import Musixmatch
import json
musixmatch = Musixmatch('<api>')
json_data = musixmatch.matcher_track_get('', '')
print(json_data['message']['body']['track']['track_name'])
print(json_data['message']['body']['track']['artist_name'])

i want to put it after yt download complete. then get metadata from api. and rename the file before it play. but i dont know where to put it. sorry im a 14 yrs old.
