### ISSUE TITLE
Add "admin mode"

### ISSUE THREAD

**Issue by vicwomg** [vicwomg/pikaraoke#12]
Some kind of admin mode would be nice. When not admin, the following features would be disabled:

- Player Control
- Queue editing
- Add 5 random songs
- Clear all
- Edit song name
- Hide all the System Info / Updates / Shutdown features

**Comment by Hartebee5t** [comment]
Loosely related to an admin-mode capability ,...
Would it be possible (or is it already) for the application to be run {full-screen or in-a-window} on the primary display of a dual-display set-up (Pi4), with the desktop left available on the secondary display? This _could_ be tied to a default admin mode for the host Pi user, running (say) in a window on the secondary display with local mouse/keyboard control.
I raise this as it might help me debug an issue that I get when I auto-run. As there's no console, when I 'Quit to console' there's no screen/debug output to give me a clue as to what's not running correctly.

**Comment by tommhendrick** [comment]
This is a very good idea. Have you started on this at all? Otherwise I might fork.

**Comment by vicwomg** [comment]
Go for it @tommhendrick ! Haven't touched this in a while. Would love to get some contributions going.

**Comment by Hartebee5t** [comment]
> Some kind of admin mode would be nice. When not admin, the following features would be disabled:
> 
> * Player Control
> * Queue editing
> * Add 5 random songs
> * Clear all
> * Edit song name
> * Hide all the System Info / Updates / Shutdown features

If someone's looking at Admin Mode features, could I request adding a Queue History list?

**Comment by vicwomg** [comment]
now live on the development branch. Just specify --admin-password on the command line to enable
