### ISSUE TITLE
Downloading new song + adding to queue: shows a blank user in the queue

### ISSUE THREAD

**Issue by vicwomg** [vicwomg/pikaraoke#123]
Downloading new song + adding to queue: shows a blank user in the queue.

**Comment by BramWerbrouck** [comment]
What is the purpose of having to different users?
    $("#queue-user").val(user)
    $("#search-user").val(user)

I guess that the queue-user is the same a s the search-user?

**Comment by vicwomg** [comment]
It's a bit poorly named, but now that I'm looking at it, these are two hidden inputs on two different forms that must be named differently in order to submit the user name with the request

queue-user: user added song from the list of pre-downloaded songs
search-user: user who added song from youtube search

But now that you mention this, I the reason this bug is ocurrring is because there's a 3rd form that's hijacking the "search-user" id value: direct youtube download user.

I'm going to refactor things a bit to make this less of a mess.
