### ISSUE TITLE
Ausome

### ISSUE THREAD

**Issue by paappraiser** [vicwomg/pikaraoke#126]
I could not find a discussions tab.  Thanks for making this. I put this together for a big party (for teens!)  and it was the hit of the evening.  We did not have Wifi so I used a old router as a hotspot and the week before used youtube DL to dump vids to a jump drive.  Major hit!  Sent coffee.

For when you dont have wifi - this as its own hotspot would be amazing. Dont know how many connections or range the pi can handle though.  A wifi scan interface would be amazing also - the pi-config sucks.

**Comment by vicwomg** [comment]
Thank you! I'm so glad it was a hit at the party.

There is a way to run as an AP. I've done it before, it was a little tricky but I actually linked it in my README:
https://github.com/vicwomg/pikaraoke#can-i-run-pikaraoke-without-a-wifinetwork-connection

**Comment by vicwomg** [comment]
not an issue, closing
