### ISSUE TITLE
Error running pip install -r requirements.txt: WARNING: "freetype-config" failed! 

### ISSUE THREAD

**Issue by lucairr** [vicwomg/pikaraoke#13]
Hi, I'm getting some errors installig the pikaraoke.
When I run the command  sudo pip install -r requirements.txt I receive this error:

    WARNING, No "Setup" File Exists, Running "config.py"
    Using UNIX configuration...

    sh: 1: freetype-config: not found
    sh: 1: freetype-config: not found
    sh: 1: freetype-config: not found

    Hunting dependencies...
    WARNING: "freetype-config" failed!
    SDL     : found 1.2.15
    FONT    : not found
    IMAGE   : not found
    MIXER   : not found
    PNG     : found
    JPEG    : found
    SCRAP   : found
    PORTMIDI: not found
    PORTTIME: not found
    FREETYPE: not found
    Missing dependencies
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Then if I try to run the pikaraoke I receive this:

pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "app.py", line 11, in <module>
    import karaoke
  File "/home/pi/Music/pikaraoke/karaoke.py", line 12, in <module>
    import qrcode
ImportError: No module named qrcode

Can u help me? Thanks

**Comment by vicwomg** [comment]
I was able to reproduce the issue. Thanks for the report! I will push a fix today

**Comment by lucairr** [comment]
Worked.
Great job
