### ISSUE TITLE
PiKaraoke startup using 0.0.0.0:5000

### ISSUE THREAD

**Issue by sromo006** [vicwomg/pikaraoke#133]
Need a way to reset the web publish on local network. Pi is connected to wifi and can browse internet but pikaraoke is not using local IP. It is only using unassigned IP of 0.0.0.0:5000

**Comment by sromo006** [comment]
Debug log file attached.

[pikaraoke.log](https://github.com/vicwomg/pikaraoke/files/6857549/pikaraoke.log)

**Comment by vicwomg** [comment]
I'm not sure understand the issue, the logs seem to indicate its rendering the correct LAN IP:

`[2021-07-21 11:51:36] DEBUG: IP address (for QR code and splash screen): 192.168.1.19`

 is the QR code on the splash screen showing 0.0.0.0:5000?
FYI, 0.0.0.0:5000 is just shorthand for serving on localhost. You can safely ignore it in the logs.

**Comment by sromo006** [comment]
It doesnt seem to host to that IP address. When I call that IP from my phone browser it says it Site cant be reached. So everything looks like it should be working but the site isnt reachable from another browser on the network. When I launch from localhost on pi it works fine. I cant figure out why site is unreachable. I even did a fresh install of everything and same thing.

**Comment by sromo006** [comment]
Splash screen shows the IP correctly and the port but get the site cant be reached from other devices on the same network.

**Comment by vicwomg** [comment]
Just to be clear, you can't reach: http://192.168.1.19:5000 ?

Can you `ping 192.168.1.19` from your computer and does it get a response?

It's also possible your router is blocking access. You might want to try launching pikaraoke with `-p 80` to put it on the more standard port 80.

**Comment by sromo006** [comment]
Pinging I get replys but first one always times out. When I change to port 80 I get site cant be reached but splash screen shows correctly.

Pinging 192.168.1.19 with 32 bytes of data:
Request timed out.
Reply from 192.168.1.19: bytes=32 time=403ms TTL=64
Reply from 192.168.1.19: bytes=32 time=5ms TTL=64
Reply from 192.168.1.19: bytes=32 time=5ms TTL=64

**Comment by vicwomg** [comment]
Try running a basic python http server with:

`python3 -m http.server 5000`

Then from one of your clients try to access http://192.168.1.19:5000 . You should see a directory listing. If you still get a site unreachable error, then I'd guess that the problem is with your router/network and not with pikaraoke.

**Comment by sromo006** [comment]
I was able to see the directory. I rebooted the wifi and pikaraoke is working now. thanks. These are helpful troubleshooting tips.
