### ISSUE TITLE
smartphone as singer/player microphone

### ISSUE THREAD

**Issue by sjuk** [vicwomg/pikaraoke#134]
Dear vicwomg, I was really happy about a new purpose for my long forgotten rpi3b: Karaoke :-)
Before forgetting my manners: Many thanks for developing pikaraoke!

When trying to use my singstar usb adapter with two microphones (working fine with performous for years) I was not able to pass the mic-in to hdmi-out. It seems to be a problem with a broken alsaloop from alsa-utils in debian buster. I started with your template image. By the way, performous is not ready for rpi yet. I tried that already.
I also tried the audio pass through with ubuntu server 20.04 (aarch64). alsaloop is working now, but it seems to need more configuration. The sound is only crackling. I don't know where to start with the configuration. Perhaps I will try to use pulseaudio instead. It comes with a higher abstraction layer and can perhaps make the configuration easier.

But when I first thought about pikaraoke which is controlled by web interface from smartphone or tablet I imagined that it would be great to use the smartphone as singer/player microphone. **Did you ever consider to add the feature to use a smartphone as singer/player microphone?** This would not be a high quality solution/workaround for the poor audio capabilities of the rpi. But it would be a funny and creative solution. **What do you think about that idea?** I'm very excited to hear from you soon. ;-)

**Comment by DanielFrankDK** [comment]
Although it's a great idea, but this would be almost impossible, mainly due to latency. Also, smartphone audio mics are not the same in all devices, so you'll never know if the audio of the mic would be lower than the audio karaoke video. The best solution would be to get a mixer, a couple of mics, and mix all the audio on the mixer instead.
