### ISSUE TITLE
Audio is distorted with VLC on Raspberry Pi 4

### ISSUE THREAD

**Issue by BeansIsFat** [vicwomg/pikaraoke#136]
VLC distorts the audio when using sudo. I've confirmed from the command line that the same track sounds fine when played by VLC without sudo.

I'm using a Raspberry Pi with audio over HDMI but there was also distortion when I forced the audio over the headphone jack by editing alsa.conf.

I don't get any distortion when using omxplayer with either `--adev hdmi` or  `--adev local`. But since I have a lot of CDG files I'd really prefer to use VLC if possible.

This is on PiKaraoke version 1.1.1 updated from 1.1.0 that was installed using the pikaraoke image. I've run setup.sh to make sure everything is installed and patched correctly.

**Comment by BeansIsFat** [comment]
After further investigation this appears to be a problem with the pikaraoke 1.1.0 OS image. I installed pikaraoke on a fresh Raspbian Lite image and was not able to reproduce the problem.

**Comment by vicwomg** [comment]
Thanks for the report. I'll see if I can replicate the issue and figure out what configuration would be causing it. Sounds vaguely familiar to the alsa issues we've seen in the past: #47

**Comment by vicwomg** [comment]
VLC removed in Pikaraoke 1.2
