### ISSUE TITLE
gunicorn requires Python '>=3.4' but the running Python is 2.7.13

### ISSUE THREAD

**Issue by paappraiser** [vicwomg/pikaraoke#14]
Hi

Running 3.5.3 on new raspbian (minimal version) and new install. Tried the workaround in the other thread, but this is stopping me.

**Comment by paappraiser** [comment]
Changed  default python to 3 reinstalled. Errors if I leave it at 3, changed back to 2. Splash screen opens but cant log in from separate device.

**Comment by vicwomg** [comment]
Thanks for the report. Just to be clear, this was a fresh Raspbian install? Pikaraoke is not python 3 compatible. As of my last check around 12/29/2019, the default python on raspbian is 2.7 but I suppose that may have changed over the new year. 

 Any specific commands, screenshots and error output would be helpful to figure out what's going on with the device not being able to connect. Does the IP shown in the upper left look like it's in your network? Also Note that the device must be on the same wifi network.

**Comment by vicwomg** [comment]
reopen if this is still an issue
