### ISSUE TITLE
requirements.txt issue re: python 3.9.7 and pygame===1.9.6

### ISSUE THREAD

**Issue by marzukia** [vicwomg/pikaraoke#147]
```
ERROR: Could not find a version that satisfies the requirement pygame==1.9.6 (from versions: 1.9.2rc1, 1.9.2, 1.9.3, 1.9.4.dev0, 1.9.4rc1, 1.9.4, 1.9.5rc1, 1.9.5rc2, 1.9.5, 1.9.6rc1, 1.9.6rc2, 1.9.6, 2.0.0.dev1, 2.0.0.dev2, 2.0.0.dev3, 2.0.0.dev4, 2.0.0.dev6, 2.0.0.dev8, 2.0.0.dev10, 2.0.0.dev12, 2.0.0.dev14, 2.0.0.dev16, 2.0.0.dev18, 2.0.0.dev20, 2.0.0.dev22, 2.0.0.dev24, 2.0.0, 2.0.1.dev1, 2.0.1, 2.0.2.dev2)
ERROR: No matching distribution found for pygame==1.9.6
```

When installing using `requirements.txt`. I had to remove the explicit version in requirements.

Using Fedora 34.

**Comment by Hartebee5t** [comment]
It seems odd that the error message quotes the _exact_ version string ("1.9.6") in the searched list that it says it can't find. Is there something wrong with Fedora's version search, or is there more than one kind of '.' (or 1 or 9 or 6) that the search distinguishes?

**Comment by vicwomg** [comment]
I noticed that too, ideally pikaraoke should move to use the latest version pygame, but last I checked it had issues with displaying image files (QR code, specifcally) on the pi. @marzukia are you on the latest version of 2.X pygame now? If so, does it seem to work as expected?

**Comment by tbelaire** [comment]
I also ran into this, and had to update to get it working on my dev machine, but I don't have my pi right now, and wasn't able to test the splash screen.

**Comment by vicwomg** [comment]
There was definitely some distinct reason we went with 1.9.6, some kind of
display issue with more recent pygame versions (I believe mainly around
rendering the qr code bitmap), but if we can get confirmation that the
latest works ok, happy to proceed with merging this.

**Comment by tbelaire** [comment]
Yeah I have my pi back and it's 
"* Failed to add service - already in use?" From pygame display init.  Which looks like they are complaining about the SDL version which ships in raspbian and it's a mess to fix. Uhg.

**Comment by vicwomg** [comment]
I recently poked around getting the latest pygame working on the 160 branch. As it turns out, Rpi Bullseye broke lots of stuff. Here's what I added to the setup-pi script to get it working:

`sudo apt-get install libjpeg-dev libsdl2-image-2.0-0 vlc python3-pip ffmpeg libsdl2-ttf-dev -y`

These might be of particular importance:
libsdl2-ttf-dev libjpeg-dev libsdl2-image-2.0-0

I kind of hate pygame at this point. Wondering lately if it makes sense to just have a HTML splash screen endpoint and show that in a kiosk-mode browser. Unfortunately that would require X11 to be installed, so the pi image would be less minimal than I'd like.

**Comment by tbelaire** [comment]
Or, it could use this to display the QR Code
https://askubuntu.com/a/755357/9744
And stay in terminal mode? Or curses or something?  I feel your pain.

I was just trying to get SDL2 working on the pi, but that basically means
compiling SDL on the pi, and I'm not sure if that's going to work for you
and how that's going to be distributable and all that.

Or perhaps load up a single frame video and display that using the same
player as the youtube videos?  Then you can re-use that.

**Comment by tbelaire** [comment]
OK I spent a good 4 hours today messing with configure scripts and such with SDL and man, it's not happy.  I finally got it working, but I think I need to reconfigure pygame.  If we can avoid messing with SDL for a release version, that's a huge plus.

**Comment by tbelaire** [comment]
This looks good

https://superuser.com/a/1558898/15735

qrencode program.  Now lets see how to just output to the tty1.  I want this to happen on boot, and I have a mostly working systemd service to launching it, so I'm going to mess about with that a bit more.

**Comment by vicwomg** [comment]
Did you try the apt installs I mentioned above? Pretty sure I fixed the latest pygame in this branch:

160-fix_pi_setup_and_requirements

Seems to be working with pygame 2.1.0 for me right now.

You do need to re-run `setup-pi.sh`to get those SDL libraries

**Comment by takoyaki17** [comment]
@vicwomg can you help me out with this?
![Screenshot (1)](https://user-images.githubusercontent.com/122594705/212256536-f7181523-5744-4971-8be3-78d70970b357.png)

**Comment by vicwomg** [comment]
pygame removed in Pikaraoke 1.2
