### ISSUE TITLE
bug on quit

### ISSUE THREAD

**Issue by BramWerbrouck** [vicwomg/pikaraoke#148]
When you use the option QUIT in admin mode, the "Now Playing icon" is still showing movement, the song/artist is still visible and the next song too (if there is a queue), this data should be empty and the now playing icon not visible

When choosing REBOOT or SHUTDOWN, this is already better, but the Next song/artist is still visible

In all cases, the queue is still filled with the songs (should be empty too)

**Comment by vicwomg** [comment]
thanks for the report. I imagine executing `k.stop()` before the restart calls on quit/shutdown/reboot  would fix this, if you want to take a shot at another pull request.

**Comment by vicwomg** [comment]
Or perhaps better yet: `k.queue_clear()`

**Comment by BramWerbrouck** [comment]
Thanks for this suggestion, I'll try this and give feedback. I already tried some other things, but mostIy the pi was stuck and I had to use a "hard reset" (power off the PI by removing the adapter).. I could not use the "reboot" or "shutdown" option anymore (read: When I pressed one of these buttons, nothing happens, except that the values in the app where NULL and the piKaraoke on the screen keeps playing)

**Comment by BramWerbrouck** [comment]
`k.queue_clear()` does do the trick :-) it works!! Thanks for this. I don’t know if it is even possible, but it would be nice to to send a notification to all the connected users (not only the admin(s)) when piKaraoke is stopped, rebooting or shutdown.

You got a message when you are the admin who execute the command, and the currently playing song is **empty** (same for the song in the queue) but for the other users, there is “_Nothing is playing right now_” and “_No song is queued_”
