### ISSUE TITLE
Feature request: search without adding a username

### ISSUE THREAD

**Issue by BramWerbrouck** [vicwomg/pikaraoke#149]
Imagine: in a group of users there is one shy man or women.. just curious.. and open the browser to connect to the piKaraoke. If he/she go to the search page to look what songs are available, the first thing that is asked is his/her name. If you don’t enter a name (cancel the prompt) you are stuck… everytime you cancel the prompt, it appears again until you enter your name.

maybe you should be able to search a song, without entering your name, but without a username, the `queue-button` should not be active (otherwise the `added by` is empty. Off course, an optional `add username` should be available (maybe on the `info page`)

**Comment by vicwomg** [comment]
Addressed in Pikaraoke 1.2. If you hit "Cancel" when prompted for name, it will generate an anonymous username
