### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by tbelaire** [vicwomg/pikaraoke#153]
Hey, I would like to try and translate the pikaraoke application so it can be used in other locales.  I'm a pyhton dev, but I haven't set up localization from scratch before.

Seems like python ships with gettext

https://docs.python.org/3/library/gettext.html

If I wrapped the strings for use in that, would you consider upstreaming the changes?

**Comment by vicwomg** [comment]
Absolutely! That would be a much welcome addition to the project

**Comment by Mc-polo** [comment]
I'm pretty newbie with tech stuff about localization, but would like to translate also this awesome software. Is there any good tutorial for that? I know linux well, but not python...

**Comment by tbelaire** [comment]
I have done some for work, but that's using their own whole system.  I'll take a crack at marking up the app and push it up to a branch so you can take a look at it this weekend. 

I'm also going to referencing the [Gnu GetText manual].

Can I ask which languages you are planning on using?  I want to get it translated into Chinese for my in-laws.

[Gnu GetText manual]: https://www.gnu.org/software/gettext/manual/index.html

**Comment by Mc-polo** [comment]
Thank you for info.

I plan to translate to Finnish. Gui doesn't have much information but it is
difficult for some to operate.



pe 3. jouluk. 2021 klo 17.23 Theo Belaire ***@***.***>
kirjoitti:

**Comment by tbelaire** [comment]
I realise now that I probably really want to localize the templates the most.  
I see some people use Flask-Babel?
https://phrase.com/blog/posts/python-localization-flask-applications/

But there's also a gettext example with Jinja https://svn.python.org/projects/external/Jinja-1.1/docs/build/i18n.html

https://jinja.palletsprojects.com/en/3.0.x/templates/#i18n


I got some translations "Added", and we can start marking the strings in the templates for translation now.
We might need to not just use serverside translations for things like the number of semitones.

https://github.com/tbelaire/pikaraoke/commit/22d043d7f908508d63ab6f9a878ca284234fd902

**Comment by tbelaire** [comment]
Alright, I think I got it working, but it's a bit messy.

Want to take a look at it now? There's still a lot of strings that need to be marked up for translation.

I chose the MSG: tag somewhat arbitrarily, if you want to change it, go ahead and I'll swap them all out.  (It's similar to what I used at work, but I see other examples using `i18n:` or `TRANSLATORS`).

**Comment by tbelaire** [comment]
I had to change the UI a bit, as "Queue" the page (noun) vs "Queue" (the verb) to add to the queue was hard to translate, as those only align in english.

So I changed to "Add to queue", and the checkboxes to "Add to queue after downloaded".

But otherwise the home and search pages should be happy.

**Comment by vicwomg** [comment]
Thank you so much for working on this, can you wrap it into a pull request?

**Comment by vicwomg** [comment]
This was merged a while ago
