### ISSUE TITLE
SMB? MKV? Audio Track selection?

### ISSUE THREAD

**Issue by jasonhpchu** [vicwomg/pikaraoke#154]
Sorry for dropping an issue like this, I couldn't find a way to contact you.
I'm looking for a KTV solution, since most of my other older solutions have gone obsolete.
Can I add or browse songs located in a network share (SMB), like my NAS?
I think it already supports MKV, I saw the comment about it.  But just to confirm can it support playing MKV?
Can it select audio tracks on the MKV?  I have instrumental and vocal tracks on the MKV.
How about KTV with left/right split tracks, can it select a single side for playback?
TIA

**Comment by vicwomg** [comment]
I encourage you to install this on a pi

- You can probably get this working by auto-mounting a r/w SMB location on a pi. Then using the `-d DOWNLOAD_PATH` option to specify the path to your smb mount. 
- Yes, mkv is supported
- No, you cannot select audio tracks or L/R channels on videos at this time. But if vlc supports it, shouldn't be hard to add at some point in the future.
