### ISSUE TITLE
setup bug python-pygame

### ISSUE THREAD

**Issue by TheTrashAcc** [vicwomg/pikaraoke#156]
**When setting up pikaraoke the following error occurs:**

```
Package python-pygame is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-pygame' has no installation candidate
```

For me the fix was to change **python-pygame** to **python3-pygame** in setup-pi.sh:

```
echo "*** INSTALLING REQUIRED BINARIES ***"
sudo apt-get install libjpeg-dev omxplayer vlc python3-pip python-pygame ffmpeg libsdl2-ttf-dev -y
```

to

```
echo "*** INSTALLING REQUIRED BINARIES ***"
sudo apt-get install libjpeg-dev omxplayer vlc python3-pip python3-pygame ffmpeg libsdl2-ttf-dev -y
```

I'm using:
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

And python version: 3.9.2

**Comment by vicwomg** [comment]
Fixed in #157
