### ISSUE TITLE
Youtube-dl downloads are very slow lately

### ISSUE THREAD

**Issue by vicwomg** [vicwomg/pikaraoke#162]
Apparently a known issue, I'm hoping youtube-dl fixes it, but seems like there are other community patches and forks that do:
https://github.com/ytdl-org/youtube-dl/issues/30354

The temporary fix is to run:
`pip3 install --force-reinstall -U git+https://github.com/ytdl-org/youtube-dl@refs/pull/30184/merge`

But that will probably not age well. If this continues to be an issue we may need to switch to [youtube-dlp
](https://github.com/yt-dlp/yt-dlp/releases)

**Comment by EsterLoken** [comment]
I mean, [this commit from 3 days ago](https://github.com/ytdl-org/youtube-dl/commit/21b759057502c6e70d51011cfb3fb86d84055182) doesn't inspire much confidence in youtube-dl. That's their primary contributor who just resigned. That leaves a _single_ core-dev who hasn't been active since Jun 28.

yt-dlp has superseded youtube-dl in terms of functionality months ago and is as far as I know a drop-in replacement. Might as well make the switch now.

**Comment by FunkeCoder23** [comment]
#166  seems to resolve this issue (and a bit more)
If it were slimmed down to just the yt-dlp replacement (and dl string replacement) it would work well and is what I did on my own copy.

**Comment by friki67** [comment]
Hi there. Complete github beginner here. How can I install this fix? I really like to have this working 100% for tonight. Thank you in advance and please forgive my ignorance.

**Comment by Neogohan1** [comment]
> #166 seems to resolve this issue (and a bit more) If it were slimmed down to just the yt-dlp replacement (and dl string replacement) it would work well and is what I did on my own copy.

Hey are you able to share how you replaced it? I'm looking to do the same as I'd like to download the high quality videos but the speed seems to be only around 80kb/s at the moment.

**Comment by FunkeCoder23** [comment]
I'll whip up a proper replacement tomorrow (with a cli arg to switch). If
you feel like venturing into the code basically just need to replace
youtube-dl with yt-dlp and change the download URL to not include the base
url

**Comment by ejwatki** [comment]
FYI: Just installed this for an evening and have to say it's brilliant! I had a similar issue - modified one line to include aria2c as an external downloader and it picked up significantly.

**Comment by vicwomg** [comment]
ok, so I was waiting to see if the dust would settle on youtube-dl and whether another group of developers would take over. However, it does seem that the community appears to be moving towards yt-dlp. Who knows if it will also go south eventually but such is the nature of such a controversial package.

PR #166 seems to have quite a bit more than just the yt-dlp fixes, I don't have a clear idea what those are. Also I need some more assurance of cross-platform support. So, I have created a new branch and PR at #173  I could use a hand in confirming these changes work in linux and windows before merging to master.

git noobs (and there seems to be a lot of those here, hi!) here's how you would switch to this branch to install and test the changes. Note: this is specific to raspberry pi, but 

cd to your pikaraoke directory, then:

```
git pull
git checkout 162-switch_to_yt-dlp
```

Next install yt-dlp:

Raspberry pi: `./setup-pi.sh`
Windows: `scoop install yt-dlp`
Linux/OSX: `pip3 install yt-dlp`

Then relaunch pikaraoke and see if things improve.

**Comment by vicwomg** [comment]
Confirmed working on Windows, will merge this to master
