### ISSUE TITLE
.cdg files queue but don't play on raspberry pi

### ISSUE THREAD

**Issue by RDoi1** [vicwomg/pikaraoke#163]
When i add mp3 + cdg files to download directory they show when i browse and allow me to queue them but they do not play, it will show it start then move on to next in queue.

Raspberry Pi4 using the Pi Image.

**Comment by vicwomg** [comment]
Appears to have been broken by this:  
https://github.com/vicwomg/pikaraoke/pull/152/files

lib/vlcclient.py#125

I will revert those changes for now

**Comment by vicwomg** [comment]
the latest pull should fix this, let me know if not

**Comment by jramboz** [comment]
I think I've spotted the problem, in the `handle_mp3_cdg` method. Looks like the logic in the updated version wasn't quite correct. Also looks like `fnmatch` should have been imported and wasn't. I'll see if I can fix it up later today.

**Comment by RDoi1** [comment]
Thanks

**Comment by akhepcat** [comment]
Grr..   I hate it when bugs slip through local QC...  :-/
