### ISSUE TITLE
Video not playing in Windows

### ISSUE THREAD

**Issue by friki67** [vicwomg/pikaraoke#168]
Pikaraoke starts, and I can connect to the web interface. When queuing a song it launches VLC, but nothing more happens. It seems like pikaraoke can't control VLC. Then I manually load the video in VLC, it launches in fullscreen and I can pause/play it from the web interface. 
VLC 3.0.16, piKaraoke downloaded last Tuesday.

So what is happening?

**Comment by jramboz** [comment]
I think pull request #167 might already have a fix for this.

**Comment by vicwomg** [comment]
I have merged #167 to master let me know if that fixes it.

**Comment by friki67** [comment]
Yes! It is fixed now. Thank you very much
