### ISSUE TITLE
"Browse" Tab on mobile interface throws internal server error

### ISSUE THREAD

**Issue by Jamalarm** [vicwomg/pikaraoke#169]
Hi,

Just installed this app, loving it so far. Thank you so much for maintaining it.

Just as a side note, I had absolutely zero luck getting it to work with Bullseye on a Rpi3. Downgrading to Buster did the trick though.

There's just one bug I'm getting. On selecting the "Browse" tab on the mobile interface, a 501 is returned and the page displays "Internal Server Error".

I managed to grab a stacktrace in a really annoying way (due to my setup it is a photo of a screen, I'm sorry!).

![image](https://user-images.githubusercontent.com/12399497/147691751-81b8e8af-a91b-4153-844b-203574635ecc.png)

My setup is a brand new Buster image from the official Rpi imager tool. The only thing I've done is `apt update`, `apt upgrade` and then installed `pikaraoke`.

Please let me know if there's any more info I can provide.

Tom

**Comment by vicwomg** [comment]
Thank you for the trace! I think other folks have reported this on reddit. Can you tell me what flask-paginate version is installed? Looks like it's doing something bad around thinking we're using Bootstrap as a css framework, when it clearly shows Bulma. 

Run this.
`pip3 show flask-paginate`

**Comment by vicwomg** [comment]
as for the bullseye issues... sorry about that. They messed up a LOT of display-related stuff... often breaking VLC playback/audio and it's been a pain to sort through. There are some tips here: #161

**Comment by Jamalarm** [comment]
Hey @vicwomg - thanks for the speedy response. Here is the `flask-paginate` output:

```
pi@pimediaserver:~ $ pip3 show flask-paginate
Name: flask-paginate
Version: 2021.12.28
Summary: Simple paginate support for flask
Home-page: https://github.com/lixxu/flask-paginate
Author: Lix Xu
Author-email: xuzenglin@gmail.com
License: BSD-3-Clause
Location: /usr/local/lib/python3.7/dist-packages
Requires: Flask
Required-by: 
```

**Comment by vicwomg** [comment]
It seems as though there's a bug in flask-paginate version 2021.12.28

Rolling back to 2021.10.29 seems to fix it. Try this and let me know if it helps:

`pip3 install flask-paginate==2021.10.29`

if so, I will force that version in the requirements.txt

**Comment by starquinius** [comment]
> It seems as though there's a bug in flask-paginate version 2021.12.28
> 
> Rolling back to 2021.10.29 seems to fix it. Try this and let me know if it helps:
> 
> `sudo pip3 install flask-paginate==2021.10.29`
> 
> if so, I will force that version in the requirements.txt

I came across your application yesterday, i also couldn't use the 'browse' option and can confirm that the suggested roll back is working for me. Thanks for the application, we are going to have a lot of fun tonight :) :) :)

**Comment by vicwomg** [comment]
Thanks for the confirmation, checking in the version requirement. Should be fixed for folks moving forward.
