### ISSUE TITLE
Using alsa creates blank screen and no audio

### ISSUE THREAD

**Issue by bennysp** [vicwomg/pikaraoke#17]
I have confirmed that the normal audio/video works through the hdmi and even 3.5mm with pikaraoke. 

I bought a HiFiBerry Soundcard Hat, however, and after making the changes to use `alsa:hw:0,0` vs `both`, I only get a blank/black screen with no audio.  I have confirmed that the sound comes out using the same omxplayer command generated by pikaraoke with no issues without pikaraoke.

Any ideas on what could cause this behavior? If I/we can get this to work, I would be happy to try and make the “output” an argument to `app.py`.

You can see the change I did here:
https://github.com/vicwomg/pikaraoke/compare/master...bennysp:master

Here is a debug output to confirm what I am seeing:

**Blank/Black Screen & no audio**
root@raspberrypi:/home/pi/pikaraoke# pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
[2020-01-18 19:12:15] DEBUG: 
    http port: 5000
    hide IP: False
    hide splash: False
    splash_delay: 4
    hide overlay: True
    download path: /usr/lib/pikaraoke/songs/
    default volume: 0
    youtube-dl path: /usr/local/bin/youtube-dl
    omxplayer path: /usr/bin/omxplayer
    log_level: 10
[2020-01-18 19:12:15] DEBUG: Fetching available songs in: /usr/lib/pikaraoke/songs/
[2020-01-18 19:12:16] DEBUG: Killing old omxplayer processes
[2020-01-18 19:12:16] DEBUG: Initializing pygame
[2020-01-18 19:12:16] DEBUG: Initializing screen mode
[2020-01-18 19:12:16] DEBUG: Done initializing splash screen
[2020-01-18 19:12:16] DEBUG: Rendering splash screen
[2020-01-18 19:12:16] DEBUG: Generating URL QR code
[2020-01-18 19:12:16] INFO: Starting PiKaraoke!
[18/Jan/2020:19:12:16] ENGINE Bus STARTING
[2020-01-18 19:12:16] INFO: [18/Jan/2020:19:12:16] ENGINE Bus STARTING
[18/Jan/2020:19:12:16] ENGINE Started monitor thread '_TimeoutMonitor'.
[2020-01-18 19:12:16] INFO: [18/Jan/2020:19:12:16] ENGINE Started monitor thread '_TimeoutMonitor'.
[18/Jan/2020:19:12:16] ENGINE Serving on http://0.0.0.0:5000
[2020-01-18 19:12:16] INFO: [18/Jan/2020:19:12:16] ENGINE Serving on http://0.0.0.0:5000
[18/Jan/2020:19:12:16] ENGINE Bus STARTED
[2020-01-18 19:12:16] INFO: [18/Jan/2020:19:12:16] ENGINE Bus STARTED
[2020-01-18 19:12:33] INFO: Adding video to queue: /usr/lib/pikaraoke/songs/Billy Joel - Uptown Girl (Karaoke)---JMpIVGv5jkE.mp4
[2020-01-18 19:12:33] DEBUG: Killing old omxplayer processes
[2020-01-18 19:12:33] INFO: Playing video: Billy Joel - Uptown Girl (Karaoke)
[2020-01-18 19:12:33] DEBUG: Player command: /usr/bin/omxplayer /usr/lib/pikaraoke/songs/Billy Joel - Uptown Girl (Karaoke)---JMpIVGv5jkE.mp4 --blank -o alsa:hw:0,0 --vol 0 --font-size 25
[2020-01-18 19:12:33] DEBUG: Rendering splash screen
[2020-01-18 19:12:33] DEBUG: Generating URL QR code
Video codec omx-h264 width 640 height 360 profile 578 fps 25.000000
Audio codec aac channels 2 samplerate 44100 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
V:PortSettingsChanged: 640x360@25.00 interlace:0 deinterlace:0 anaglyph:0 par:1.25 display:0 layer:0 alpha:255 aspectMode:0
[2020-01-18 19:13:08] INFO: Clearing queue!
[2020-01-18 19:13:08] INFO: Skipping: Billy Joel - Uptown Girl (Karaoke)
[18/Jan/2020:19:13:08] ENGINE Bus STOPPING
[2020-01-18 19:13:08] INFO: [18/Jan/2020:19:13:08] ENGINE Bus STOPPING
[18/Jan/2020:19:13:08] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 5000)) shut down
[2020-01-18 19:13:08] INFO: [18/Jan/2020:19:13:08] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 5000)) shut down
[18/Jan/2020:19:13:08] ENGINE Stopped thread '_TimeoutMonitor'.
[2020-01-18 19:13:08] INFO: [18/Jan/2020:19:13:08] ENGINE Stopped thread '_TimeoutMonitor'.
[18/Jan/2020:19:13:08] ENGINE Bus STOPPED
[2020-01-18 19:13:08] INFO: [18/Jan/2020:19:13:08] ENGINE Bus STOPPED
[18/Jan/2020:19:13:08] ENGINE Bus EXITING
[2020-01-18 19:13:08] INFO: [18/Jan/2020:19:13:08] ENGINE Bus EXITING
[18/Jan/2020:19:13:08] ENGINE Bus EXITED
[2020-01-18 19:13:08] INFO: [18/Jan/2020:19:13:08] ENGINE Bus EXITED
Stopped at: 00:00:00
[18/Jan/2020:19:13:08] ENGINE Waiting for child threads to terminate...
[2020-01-18 19:13:08] INFO: [18/Jan/2020:19:13:08] ENGINE Waiting for child threads to terminate...
have a nice day ;)

**Works as expected**
root@raspberrypi:/home/pi/pikaraoke# /usr/bin/omxplayer "/usr/lib/pikaraoke/songs/Billy Joel - Uptown Girl (Karaoke)---JMpIVGv5jkE.mp4" --blank -o alsa:hw:0,0 --vol 0 --font-size 25
Video codec omx-h264 width 640 height 360 profile 578 fps 25.000000
Audio codec aac channels 2 samplerate 44100 bitspersample 16
Subtitle count: 0, state: off, index: 1, delay: 0
V:PortSettingsChanged: 640x360@25.00 interlace:0 deinterlace:0 anaglyph:0 par:1.25 display:0 layer:0 alpha:255 aspectMode:0
have a nice day ;)

**Comment by Hartebee5t** [comment]
> I have confirmed that the normal audio/video works through the hdmi and even 3.5mm with pikaraoke.
> 
> I bought a HiFiBerry Soundcard Hat, however, and after making the changes to use `alsa:hw:0,0` vs `both`, I only get a blank/black screen with no audio. I have confirmed that the sound comes out using the same omxplayer command generated by pikaraoke with no issues without pikaraoke.
> 
> Any ideas on what could cause this behavior? If I/we can get this to work, I would be happy to try and make the “output” an argument to `app.py`.
> 
> You can see the change I did here:
> [master...bennysp:master](https://github.com/vicwomg/pikaraoke/compare/master...bennysp:master)
> 
> Here is a debug output to confirm what I am seeing:
> 
> **Blank/Black Screen & no audio**
> root@raspberrypi:/home/pi/pikaraoke# pygame 1.9.4.post1
> Hello from the pygame community. https://www.pygame.org/contribute.html
> [2020-01-18 19:12:15] DEBUG:
> http port: 5000
> hide IP: False
> hide splash: False
> splash_delay: 4
> hide overlay: True
> download path: /usr/lib/pikaraoke/songs/
> default volume: 0
> youtube-dl path: /usr/local/bin/youtube-dl
> omxplayer path: /usr/bin/omxplayer
> log_level: 10
> [2020-01-18 19:12:15] DEBUG: Fetching available songs in: /usr/lib/pikaraoke/songs/
> [2020-01-18 19:12:16] DEBUG: Killing old omxplayer processes
> [2020-01-18 19:12:16] DEBUG: Initializing pygame
> [2020-01-18 19:12:16] DEBUG: Initializing screen mode
> [2020-01-18 19:12:16] DEBUG: Done initializing splash screen
> [2020-01-18 19:12:16] DEBUG: Rendering splash screen
> [2020-01-18 19:12:16] DEBUG: Generating URL QR code
> [2020-01-18 19:12:16] INFO: Starting PiKaraoke!
> [18/Jan/2020:19:12:16] ENGINE Bus STARTING
> [2020-01-18 19:12:16] INFO: [18/Jan/2020:19:12:16] ENGINE Bus STARTING
> [18/Jan/2020:19:12:16] ENGINE Started monitor thread '_TimeoutMonitor'.
> [2020-01-18 19:12:16] INFO: [18/Jan/2020:19:12:16] ENGINE Started monitor thread '_TimeoutMonitor'.
> [18/Jan/2020:19:12:16] ENGINE Serving on http://0.0.0.0:5000
> [2020-01-18 19:12:16] INFO: [18/Jan/2020:19:12:16] ENGINE Serving on http://0.0.0.0:5000
> [18/Jan/2020:19:12:16] ENGINE Bus STARTED
> [2020-01-18 19:12:16] INFO: [18/Jan/2020:19:12:16] ENGINE Bus STARTED
> [2020-01-18 19:12:33] INFO: Adding video to queue: /usr/lib/pikaraoke/songs/Billy Joel - Uptown Girl (Karaoke)---JMpIVGv5jkE.mp4
> [2020-01-18 19:12:33] DEBUG: Killing old omxplayer processes
> [2020-01-18 19:12:33] INFO: Playing video: Billy Joel - Uptown Girl (Karaoke)
> [2020-01-18 19:12:33] DEBUG: Player command: /usr/bin/omxplayer /usr/lib/pikaraoke/songs/Billy Joel - Uptown Girl (Karaoke)---JMpIVGv5jkE.mp4 --blank -o alsa:hw:0,0 --vol 0 --font-size 25
> [2020-01-18 19:12:33] DEBUG: Rendering splash screen
> [2020-01-18 19:12:33] DEBUG: Generating URL QR code
> Video codec omx-h264 width 640 height 360 profile 578 fps 25.000000
> Audio codec aac channels 2 samplerate 44100 bitspersample 16
> Subtitle count: 0, state: off, index: 1, delay: 0
> V:PortSettingsChanged: 640x360@25.00 interlace:0 deinterlace:0 anaglyph:0 par:1.25 display:0 layer:0 alpha:255 aspectMode:0
> [2020-01-18 19:13:08] INFO: Clearing queue!
> [2020-01-18 19:13:08] INFO: Skipping: Billy Joel - Uptown Girl (Karaoke)
> [18/Jan/2020:19:13:08] ENGINE Bus STOPPING
> [2020-01-18 19:13:08] INFO: [18/Jan/2020:19:13:08] ENGINE Bus STOPPING
> [18/Jan/2020:19:13:08] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 5000)) shut down
> [2020-01-18 19:13:08] INFO: [18/Jan/2020:19:13:08] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 5000)) shut down
> [18/Jan/2020:19:13:08] ENGINE Stopped thread '_TimeoutMonitor'.
> [2020-01-18 19:13:08] INFO: [18/Jan/2020:19:13:08] ENGINE Stopped thread '_TimeoutMonitor'.
> [18/Jan/2020:19:13:08] ENGINE Bus STOPPED
> [2020-01-18 19:13:08] INFO: [18/Jan/2020:19:13:08] ENGINE Bus STOPPED
> [18/Jan/2020:19:13:08] ENGINE Bus EXITING
> [2020-01-18 19:13:08] INFO: [18/Jan/2020:19:13:08] ENGINE Bus EXITING
> [18/Jan/2020:19:13:08] ENGINE Bus EXITED
> [2020-01-18 19:13:08] INFO: [18/Jan/2020:19:13:08] ENGINE Bus EXITED
> Stopped at: 00:00:00
> [18/Jan/2020:19:13:08] ENGINE Waiting for child threads to terminate...
> [2020-01-18 19:13:08] INFO: [18/Jan/2020:19:13:08] ENGINE Waiting for child threads to terminate...
> have a nice day ;)
> 
> **Works as expected**
> root@raspberrypi:/home/pi/pikaraoke# /usr/bin/omxplayer "/usr/lib/pikaraoke/songs/Billy Joel - Uptown Girl (Karaoke)---JMpIVGv5jkE.mp4" --blank -o alsa:hw:0,0 --vol 0 --font-size 25
> Video codec omx-h264 width 640 height 360 profile 578 fps 25.000000
> Audio codec aac channels 2 samplerate 44100 bitspersample 16
> Subtitle count: 0, state: off, index: 1, delay: 0
> V:PortSettingsChanged: 640x360@25.00 interlace:0 deinterlace:0 anaglyph:0 par:1.25 display:0 layer:0 alpha:255 aspectMode:0
> have a nice day ;)

I had some problems with Bluetooth a couple of weeks ago. Not yet fully resolved but worked-around. I don't believe mine is a PiKaraoke problem per se, but a Pi config problem (more likely...). 

For some reason, Bluetooth reports it's paired on startup, but it isn't really. I've found that if I select another audio sink (e.g. HDMI) after start-up, and then reselect the Bluetooth speaker before launching PiKaraoke it works fine.
Still investigating but try this. It may be a clue for those who know about such things.
More detail tomorrow.

**Comment by bennysp** [comment]
Thanks @Hartebee5t , but do you see the black screen after trying to add to queue? I do not have any other devices other than the hat/soundcard and the same omxplayer command works outside of pikaraoke.

I am suspecting something with pygame, but I have not figured that part out yet.

Thanks
ben

**Comment by vicwomg** [comment]
Hm, not sure... 

Perhaps it's possible that the increased memory overhead is exhausting the GPU memory?

> sudo nano /boot/config.txt
> gpu_mem=192

**Comment by vicwomg** [comment]
You could also try forcing pygame to only load needed modules and omit any modules related to audio

Try replacing line 154:
```pygame.init()```

With something like:
```
pygame.font.init()
pygame.mouse.init()
pygame.display.init()
pygame.image.init()
pygame.transform.init()
```

(I think that's all the modules pikaraoke needs, but could be missing a couple. Don't have it in front of me to test.)

**Comment by Hartebee5t** [comment]
> Thanks @Hartebee5t , but do you see the black screen after trying to add to queue? I do not have any other devices other than the hat/soundcard and the same omxplayer command works outside of pikaraoke.
> 
> I am suspecting something with pygame, but I have not figured that part out yet.
> 
> Thanks
> ben

Sorry, yes I also see the black screen (and no audio, as if the whole thing is waiting for something to happen before proceeding) if I don't do the de-select/re-select of Bluetooth sink between starting up my Pi and launching PiKaraoke.
I reckon the pygame hypothesis is plausible but I'm unlikely to have an opportunity to try @vicwomg's tweak suggestions today.

**Comment by bennysp** [comment]
@Hartebee5t and @vicwomg, thanks. I will give this all a shot!

**Comment by bennysp** [comment]
@vicwomg - you are genius!
See the compare... I checked the other modules and they don't have init loads (got errors). I came down to only doing inits on these two and bam, everything works!

Not sure if you or @Hartebee5t are able to test that the `both` setting still works by referencing these modules only?

I have some family users testing this setup out over the weekend, so @vicwomg, I will try to contribute back the ability to specify your sound device and submit a PR.

As always great work and thanks for the quick tip!

**Comment by vicwomg** [comment]
@bennysp  Great to know. Give a test run and if it looks to be holding up well I'll pull that in. Seems beneficial to everyone to keep the modules to a minimum anyway.

**Comment by bennysp** [comment]
Agreed

**Comment by Hartebee5t** [comment]
> Not sure if you or @Hartebee5t are able to test that the `both` setting still works by referencing these modules only?

I was able to try out the reduced .init solution for pygame (your edits around line 154 of karaoke.py) without editing the "both" part.  It worked insofar as it allowed the video to play (so it resolved the black screen lockup), but the sound over Bluetooth was awful (choppy and staccato). 
I was able to get normal sound again by reverting to my de-select/re-select Bluetooth sink workaround prior to launching PiKaraoke, but the lack of black screen is definitely significant progress (thanks again @vicwomg !).
I hope to check whether applying the "both" edit (line 325) resolves the choppy Bluetooth audio without the de-select/re-select step later this evening.  If that works, I should be able finally to get my RPi4 headlessly feeding PiKaraoke audio from power-on to the Bluetooth-enabled Line-In channel on my wireless-mic receiver. 
Watch this space...

**Comment by Hartebee5t** [comment]
Incidentally (a tad off-topic) I found last night that I needed to use the 'Update youtube-dl' feature from the Info screen (for my first time since initial installation in early December) to get new song content downloads to work again. It seems "they" had tweaked their formats in the week or two (working version date-stamped 24-Jan).

**Comment by bennysp** [comment]
@Hartebee5t - same here... the day of the friends/family were to use it, I panicked and found the same bug for the update youtube-dl and redownloaded because they just released the fix. There has been a lot happening due to key libraries for Python where they have stopped support (rightly so) to only support Python3.

@vicwomg the testing worked flawlessly. I will work on getting it as an argument so you can choose your "output device", but I am not sure if you want to minimize the packages per the above thread in the meantime?

**Comment by asum** [comment]
> @vicwomg - you are genius!
> See the compare... I checked the other modules and they don't have init loads (got errors). I came down to only doing inits on these two and bam, everything works!
> 
> [master...bennysp:master](https://github.com/vicwomg/pikaraoke/compare/master...bennysp:master)

Just to let you know, I've tried the two changes proposed by @vicwomg and @bennysp for the "pygame.init" replacements and "alsa:hw:0,0" output for omxplayer, and they work great for a JustBoom DAC HAT as well!

**Comment by bennysp** [comment]
That is great to hear @asum . 

Apologies @vicwomg that I have not had a chance to incorporate and add this as an argument yet. I just got a new Pi and should be able to test this further with a "default" setup too.

**Comment by vicwomg** [comment]
Well I think we all have a little extra time these days. I addressed this with an additional --alsa-fix parameter.

**Comment by bennysp** [comment]
Thanks @vicwomg !
