### ISSUE TITLE
After updating on Pi4 the splash screen loads and that is all

### ISSUE THREAD

**Issue by WhatWhyIT** [vicwomg/pikaraoke#172]
Updated after offline for several months.

First run, it seemed to work, queued a song but it never played.

Then another reboot the splash screen loads on the pi4 however the  website portion never seems to load.

add -l 10 to the run command however I can't seem to find where the debug output is saved.

**Comment by vicwomg** [comment]
Thanks for the report. 

It would be very helpful to see the stack trace from the failure. Where the log goes depends on how you have autolaunch set up. If you used this launch command from the README

```
# start pikaraoke on startup / logging
/usr/bin/python3 /home/pi/pikaraoke/app.py >> /var/log/pikaraoke.log 2>&1 &
```

Then it's going to `/var/log/pikaraoke.log`

If you can't find the log, then start pikaraoke manually from the command line. It will show the log on the terminal output.

**Comment by WhatWhyIT** [comment]
This is how I ran it historically -- #!/bin/sh
#This launches PiKaraoke
cd ~/pikaraoke/
sudo python3 app.py --adev alsa:hw:0,0 --high-quality --port 80

-----

I can add "--l 10"  and I can get splash screen however the page doesn't respond.

Reviewing the console looks like it isn't binding to an IP although I'm using VNC to connect to it the PI remotely.

----- Here is the console output----

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
[2022-01-01 18:14:43] INFO: Fetching available songs in: /usr/lib/pikaraoke/songs/
[2022-01-01 18:14:46] INFO: VLC command base: /usr/bin/vlc -f --play-and-exit --extraintf http --http-port 5002 --http-password SIUVKDqxC3HykFei73Ghk2LjdrIKjxPY --no-embedded-video --no-keyboard-events --no-mouse-events --mouse-hide-timeout 0 --video-on-top --no-video-title --mouse-hide-timeout 0
[01/Jan/2022:18:14:46] ENGINE Bus STARTING
[2022-01-01 18:14:46] INFO: [01/Jan/2022:18:14:46] ENGINE Bus STARTING
[01/Jan/2022:18:14:46] ENGINE Started monitor thread '_TimeoutMonitor'.
[2022-01-01 18:14:46] INFO: [01/Jan/2022:18:14:46] ENGINE Started monitor thread '_TimeoutMonitor'.
[01/Jan/2022:18:14:46] ENGINE Serving on http://0.0.0.0
[2022-01-01 18:14:46] INFO: [01/Jan/2022:18:14:46] ENGINE Serving on http://0.0.0.0
[01/Jan/2022:18:14:46] ENGINE Bus STARTED
[2022-01-01 18:14:46] INFO: [01/Jan/2022:18:14:46] ENGINE Bus STARTED
[2022-01-01 18:14:46] INFO: Starting PiKaraoke!

----

If I add ">> /var/log/pikaraoke.log 2>&1 & "  to the end of my startup command it won't launch.

**Comment by WhatWhyIT** [comment]
ok well... it loaded once and I queued a song.  I've been tweaking the startup command using --log-level 10 and got it to load up using "rt 80 --log-level 10 >> karaoke.log.txt" However the only thing written to the txt file is ... 
-------------
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
-------------

The console output has much more info however not much different than above.

**Comment by vicwomg** [comment]
Just launch manually.
`sudo python3 app.py --adev alsa:hw:0,0 --high-quality --port 80 --log-level 10`

Use the app until you enounter the error. Then quit pikaraoke. Read the console log output and look and see if there are any stack traces. That's what I need to see to properly debug this.

**Comment by vicwomg** [comment]
Come to think of it, I'm not even sure what you mean by "the website portion never seems to load", pictures, screenshots, stack traces, error messages please

**Comment by WhatWhyIT** [comment]
It's interesting.

When I say the website portion never loads, I can't access the the pikaraokee app on my smartphone. (Iphone 12). The splash page comes up showing the QR code however after scanning and navigating to the ip/url it says page not responding.
--------
I did find a workaround. Browsing to the page via localhost. and playing queueing a song. after this I did see a vnc network privacy alert window pop up behind the vlc player I'm not able to get a screen shot of it.

After queueing a song the website started working from my smartphone. Here is a screen shot of the console output. However same result with the txt file.. no output...

![image](https://user-images.githubusercontent.com/76672166/147865112-5617431c-c753-4d49-8330-774a936c7d1b.png)

**Comment by vicwomg** [comment]
picture of the splash screen? What IP is it reporting in under the QR code?

**Comment by WhatWhyIT** [comment]
I took a picture from my phone…




And the other of the splash screen.
![Uploading 5119ED75-73B3-4CBA-B910-45C2B4163893.jpeg…]()

**Comment by WhatWhyIT** [comment]
![424481F0-2AF1-4DF0-944B-8E6B34C40312](https://user-images.githubusercontent.com/76672166/147865191-d0c22c69-7a8d-4314-8bd1-7d977c65351d.jpeg)

**Comment by vicwomg** [comment]
Have you tried it without --port 80 (defaults to port 5000)? I wonder if there's some kind of firewall or conflict on your network.

Also, what did you mean by "Updated after offline for several months", what did you update? Pikaraoke or Raspberry Pi OS or both? Did you re-run ./setup-pi.sh?

**Comment by WhatWhyIT** [comment]
I was just about to say it was working fine, but did one more reboot…

back to not working.

I’ll not fiddle with anything without directions… here is a picture of the console with the QR code screen behind it and my smart phone saying page not responding.
![Uploading 3566CCC2-5A9A-43C2-8573-988C9C478B4A.jpeg…]()

**Comment by WhatWhyIT** [comment]
![EE2B3C94-C359-4605-9B9C-05DDEB9FE9F2](https://user-images.githubusercontent.com/76672166/147865506-eb993a5d-3776-4cd4-9d86-e1c16cdba061.png)

**Comment by WhatWhyIT** [comment]
Updated the PI OS  and PiKaraokee,

Initially I did NOT re-run "./setup-pi.sh" 

Troubleshooting last night, I DID re-run "./setup-pi.sh"  though.

From my troubleshooting this evening, if I navigate to localhost on the pi, then i'll be able to connect to the page via my smartphone.

**Comment by WhatWhyIT** [comment]
Meh, i'll just connect to localhost when I launch it. 

The debugging doesn't seem to provide me any info, so unless you see something useful, I'm not getting anything we can troubleshoot.

**Comment by WhatWhyIT** [comment]
Blah, it was working, played one song.. now not working.. even locally via localhost. not responding, now it's working via localhost and from my phone.

![image](https://user-images.githubusercontent.com/76672166/147866245-a54634c8-fba7-4840-a0de-3fd277ab231b.png)

**Comment by WhatWhyIT** [comment]
Unable to find any definitive reasons for the behavior. Until I can find something useful will close.
