### ISSUE TITLE
Is it feasible to clone the karaoke-video out on a(n) RPi4's second HDMI socket?

### ISSUE THREAD

**Issue by Hartebee5t** [vicwomg/pikaraoke#18]
Is it possible to configure a Raspberry Pi4 for dual-screen video playback (i.e. cloning the karaoke lyrics onto a second monitor) on a Raspberry Pi4 using the second HDMI output)?
I've tried several screen-extension options and while they replicate the desktop background (and in one case even replicated the icons on that desktop), when PiKaraoke is run the logo/QR-code display screen is expanded sideways to fill the two monitors as one super-wide Extended Desktop with the logo divided across their  shared boundary, and the karaoke lyrics video still only appears on the primary monitor.

Does anyone know of a way to clone the karaoke visuals to both HDMI outputs?
e.g. maybe as a modification to the omxplayer launch command?

I know there's something 'special' about the way the karaoke visuals are displayed, as I had tried RealVNC to do the cloning and had to apply an Advanced Option in RealVNC Server to get it to render the lyrics video stream at all (otherwise it just VNC'd the logo screen). Does this observation provide any clues to how a cloned video stream might be routed through the second HDMI?
(Even with the advanced mode applied the results with RealVNC were not great - if there's any background graphics movement at all the latency, block-artefacts and frame-dropping made it unusable)

Thanks in anticip...

**Comment by Hartebee5t** [comment]
> Is it feasible ...? 
Apparently it is, and I've figured out a way to do it !

I'm convinced this is a total overkill, but by doubling-up on the instances of subprocess.Popen calls which invoke omxplayer I can play two concurrent video streams - the existing one (unchanged) to the default HDMI0 port and the other via '--display 7' to HDMI1 port.  The use of a second PIPEd subprocess.Popen also requires some collateral tweaks to correctly handle the file-playing detection, skip, pause & restart functions so they apply to both streams.

Here's an attempt at the code snippets (all within karaoke.py) - I've yet to master the master compare feature here...
`
[...]

class Karaoke:

    :
    process = None
    process2 = None      # New init assignment (at line 27)
    :
    def play_file(self, file_path):
        :
        cmd = [ ...
                 "-o", "both",
                     ... ]     # existing cmd line unchanged (at original line 325, 
                              # incl audio-out arg "both", or your own "alsa:xxxx" Bluetooth device name)
        cmd2 = [self.player_path,file_path,
                 "--blank",
                 "-o", "local",
                 "-I",
                 "--display", "7"]     # new cmd2 definition for 2nd display (dispmanx HDMI1 port = 7,
                                       #       and audio-out arg "local" to avoid double audio)
        :
        self.process = subprocess.Popen(cmd, stdin=subprocess.PIPE,)   # existing .Popen line 
                                                                   # (at original line 331)
        self.process2 = subprocess.Popen(cmd2, stdin=subprocess.PIPE,)   # new .Popen line 
        :
    def is_file_playing(self):
        if ((self.process == None) and (self.process2 == None)):
            :
            return False
        elif ((self.process.poll() == None) or (self.process2.poll() == None))
            return True
        :
    def skip(self):
        :
            self.process.stdin.write("q") 
            self.process2.stdin.write("q") 
            :
    def pause(self):
        :
            self.process.stdin.write("p") 
            self.process2.stdin.write("p") 
            :
            # vol_up and vol_down equivalents not needed (unless "local" is fed to a speaker)
    :
    def restart(self):
        :
            self.process.stdin.write("i") 
            self.process2.stdin.write("i") 
            :
`
I still reckon there has to be a simpler way to clone one stream out of both HDMIs (as this way appears to provide a way to send different streams out of them). If anyone can tell me the simpler way I'm all ears.

**Comment by vicwomg** [comment]
thanks for figuring this out

adding: "--display", "7"

Seems backwards compatible with my pi3. It just plays out of the single hdmi as expected. If you can confirm this indeed allows both to work on pi4 I can add it as an option

I'm not concerned with double audio. You could always just mute the second display right? Or are you detecting a performance hit when it streams double audio?

**Comment by Hartebee5t** [comment]
Yes it definitely feeds both monitors, and for karaoke tracks they're near-enough synchronised not to be noticeable.
My double-stream concern was more with the inefficiency of processing two identical instances of HDMI video (not the audio) where some sort of copy or clone action seems so much more natural/sensible and less wasteful.
I've also noticed some hints of juddering of video feed if I run this dual-monitor mod with only one monitor connected.

**Comment by vicwomg** [comment]
Support dual screen hdmi video output on pi4 with --dual-screen #18
