### ISSUE TITLE
Feature Request: Volume Slide Bar or output level indicator

### ISSUE THREAD

**Issue by Romeo1984** [vicwomg/pikaraoke#182]
Would be nice to have some way of knowing where the volume is set under the Hone Screen Player Control, especially when everybody has access to the player control.

**Comment by xuancong84** [comment]
@Romeo1984 , I have implemented this feature and posted a pull-request, please look at my fork at https://github.com/xuancong84/pikaraoke
Take note that VLC volume level can well exceed 100%, (e.g., using HTTP API, it can reach even 800% by directly multiplying the input waveform by 8 (this will cause aggressive aliasing with PCM values exceeding integer max clamped at int max), and there is no limit to the volume level. Thus, it is not appropriate for me to put a slider for volume limiting the range from 0-100 or 0-200. There are other more useful features such as pitch-shift without restart from beginning, that we can improve on top of it.

**Comment by Romeo1984** [comment]
> @Romeo1984 , I have implemented this feature and posted a pull-request, please look at my fork at https://github.com/xuancong84/pikaraoke Take note that VLC volume level can well exceed 100%, (e.g., using VLC HTTP API, it can reach even 800% by directly multiplying the input waveform by 8 (this will cause aggressive aliasing with PCM values exceeding integer limit clamped at int max/min), and there is no limit to the volume level. Thus, it is not appropriate for me to put a slider to limit volume into the range from 0-100 or 0-200. There are other more useful features such as pitch-shift without restart from the beginning, that we can improve on top of it.
Thank you! Yes, I noticed that I have to strike a careful balance between having the native pi 3.5 audio output loud enough for the downstream audio device to process, but have the pikaraoke volume low enough not to overdrive the speakers and cause distortion. This is the root of my request - so I can visually see where the pikaraoke app is set to.

**Comment by vicwomg** [comment]
Added in latest pikaraoke 1.2
