### ISSUE TITLE
Local library handling

### ISSUE THREAD

**Issue by nubbyless** [vicwomg/pikaraoke#183]
Not an issue but I see no mention of how local libraries are handled I have over 80,000 cdg titles on a USB drive when searching will it search local first then stop if it is found or will it still search YouTube is there an option somewhere to use only local library and no YouTube

Thanks
Fred

**Comment by vicwomg** [comment]
Local results are shown in an autocomplete drop-down where they can be
selected. If no match is found then pressing the search button will query
YouTube.

**Comment by nubbyless** [comment]
Thank you great project and thanks for the hard work looking forward to seeing it grow.
