### ISSUE TITLE
downloads folder 

### ISSUE THREAD

**Issue by nubbyless** [vicwomg/pikaraoke#186]
Hi not sure if im doing something wrong or not if i quit pikaraoke from the web interface and then run the command sudo python3 app.py -d /media/ktv/karaoke it will scan my folder and start pikaraoke and all my songs will be there but if i reboot and it restarts on its own the songs are gone is there a way to make this usb drive the permanent download location? a file i can edit or do i need it to scan at boot everytime? also please inform me if there is another forum for support as i know github issues are really not for support 

thanks 
fred

**Comment by vicwomg** [comment]
Edit the `/etc/rc.local` file. this is where the command to auto launch on startup is. You can add your -d parameter there and it should work.

**Comment by nubbyless** [comment]
Ok I have it working now but now my issue is the wifi takes longer then a few seconds to connect can I adjust the time it waits for an IP before starting to longer then 10 seconds?

**Comment by nubbyless** [comment]
Thank you
