### ISSUE TITLE
Search doesn’t like inverted commas

### ISSUE THREAD

**Issue by djlongy** [vicwomg/pikaraoke#19]
When using inverted commas in the search field it just errors out.
Example:
Nothing’s Gonna change my love for you

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by Hartebee5t** [comment]
Not sure why mine phone's different but I'm not seeing this error, and search strings with apostrophes work fine.
This appears to be an OS feature on the communicating client device. The search works using an Android phone (v8.0.0 Android on Samsung Galaxy S7) but I get your reported "Internal Server Error" if I try the same search (just the word "Nothing's ") on an iPad Mini 4 (s/w 13.5.1). It's that alien technology getting in the way again...

**Comment by djlongy** [comment]
Come to think of it, I think you’re right, as I’ve only seen this happen on all iOS devices, iPhone 7, X and XS.

**Comment by Hartebee5t** [comment]
Alternatively it could be a Safari quirk, rather than iOS-specific (if they don't amount to the same thing, under the hood)

**Comment by vicwomg** [comment]
Android perhaps defaults to a single quote, which is better handled. iOS may default to apostrophe/inverted comma probably falls into some special character set. I thought I fixed these sorts of unicode mangling issues, but I'll have to have another look

**Comment by vicwomg** [comment]
Should be fixed in latest pull, you will need to rerun:
`sudo pip install -r requirements.txt`
