### ISSUE TITLE
Enhancement Suggestion: Use database in indexing the songs

### ISSUE THREAD

**Issue by troy-lim** [vicwomg/pikaraoke#190]
I know that this feature needs a lot of work but I think it would be cool if this is implemented. :)

By using some kind of database in indexing songs eliminates the necessity of renaming the actual file in editing. The database will just point the edited song name to the actual file itself (not renaming the actual file). In this case, downloading duplicate songs from youtube can be avoided especially if you try to download multiple playlists with some duplicate song in the advanced mode. 

Downloading playlists with duplicate songs in one instance won't take advantage of this. But imagine if you want to build a large library of songs and want to organize it by renaming. After organizing the songs, you wouldn't know if you downloaded a duplicate song as some playlists have hundreds or even thousands of songs.

**Comment by vicwomg** [comment]
Dup of #103
