### ISSUE TITLE
Add touch log file to Readme 

### ISSUE THREAD

**Issue by Romeo1984** [vicwomg/pikaraoke#192]
Fresh build on Bullseye. Tried executing the recommended start command and got permission denied. Need to add this procedure:

```
pi@raspberrypi:~ $ sudo /usr/bin/python3 /home/pi/pikaraoke/app.py >> /var/log/pikaraoke.log 2>&1 &                                             [1] 2435
pi@raspberrypi:~ $ -bash: /var/log/pikaraoke.log: Permission denied
[1]+  Exit 1                  sudo /usr/bin/python3 /home/pi/pikaraoke/app.py >> /var/log/pikaraoke.log 2>&1
pi@raspberrypi:~ $ sudo touch /var/log/pikaraoke.log
pi@raspberrypi:~ $ sudo chmod 666 /var/log/pikaraoke.log
pi@raspberrypi:~ $ ls -l /var/log/pikaraoke.log
-rw-rw-rw- 1 root root 0 Feb  8 20:46 /var/log/pikaraoke.log
pi@raspberrypi:~ $ sudo /usr/bin/python3 /home/pi/pikaraoke/app.py >> /var/log/pikaraoke.log 2>&1 &
[1] 2459
```

**Comment by xuancong84** [comment]
sudo /usr/bin/python3 /home/pi/pikaraoke/app.py >> /var/log/pikaraoke.log 2>&1 &
by default, it is logically:
(sudo /usr/bin/python3 /home/pi/pikaraoke/app.py) >> /var/log/pikaraoke.log 2>&1 &
Since normal user cannot write /var/log, of course permission denied.

**Comment by vicwomg** [comment]
Thanks for explaining @xuancong84! 

Also that command is meant to go in your /etc/rc.local which would have sudo permissions
