### ISSUE TITLE
× python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by kungfuk** [vicwomg/pikaraoke#195]
Trying to install this on windows and am having trouble when going to the pikaraoke directory and entering "pip3 install -r requirements.txt" it only outputs an error

**Comment by vicwomg** [comment]
Please install pip3 and try again. When reporting issues, always include the error messages

**Comment by hadukn88** [comment]
Hi Vic,
Having the same issue with egg_info when running pip install -r requirements.txt in windows.
screenshot below. 

When running 'python3 app.py -d <song folder location>', i get the logo, however no QRcode or link.

I've tried updating and downgrading my python, anaconda to miniconda. any thoughts?
Any thoughts?

![pikaraoke-image01](https://github.com/vicwomg/pikaraoke/assets/147293139/d2d359e2-4024-477a-8808-df5f1e3ce44a)

**Comment by vicwomg** [comment]
Does it work if if you remove "futures" from the requirements.txt file? I wonder if futures is even required anymore now that everyone should be running on python 3
