### ISSUE TITLE
omxplayer removed from 2022-04-04 debian

### ISSUE THREAD

**Issue by tbelaire** [vicwomg/pikaraoke#198]
setup-py.sh will fail with 

```
Package omxplayer is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

**Comment by troy-lim** [comment]
use VLC
edit setup-py.sh. on line 16 remove omxplayer
It should be like this

`sudo apt-get install libjpeg-dev vlc python3-pip python3-pygame ffmpeg libsdl2-ttf-dev -y`

save then try again.

**Comment by tbelaire** [comment]
Yeah, I know how to fix it, but I'm considering a patch, though it might still want to install it on older raspian installs?  I'm not sure what's the best way to handle optional deps which don't work on the new debian.

**Comment by gilgougnot** [comment]
hi,
can we have that fixed as a patch ?
Or at least documented in the readme ? 
Fresh installing on a pi3, I had to come here for a solution which is not user friendly.

**Comment by vicwomg** [comment]
Sure thing, I've just removed the dependency for now and pushed to master. We'll have to follow up with deprecating it from the project which will probably be a larger task.

**Comment by gilgougnot** [comment]
ohh nice, so reactive, thx !
