### ISSUE TITLE
Issue: Image doesn't work on Raspi 4 - Version B - 8GB

### ISSUE THREAD

**Issue by dassaffe** [vicwomg/pikaraoke#201]
Tried to install the image. The flashing-process went smooth, but Raspi 4 (B, 8GB) doesn't load it up. I tried the image on an older Raspi and there it works fine. It is stuck with the error-message **start4.elf**. Any workarounds? Going to try a manual installation now.

**Comment by vicwomg** [comment]
Darn, I think that message means that version of buster is not supported on that particular version of the Pi. Weird, since it works on my Pi 4 model B 2GB.... is the 8GB version really that much more restrictive? Surprising. 

Let me know if the latest legacy Buster version works (I do not recommend installing Bullseye due to vlc compatibility issues)

**Comment by dassaffe** [comment]
Sorry for the stupid question, but what is Legacy Buster? 
I also tried the manual installation afterwards, which worked up to the point that I was able to start the App.
However, i wasn't able to convert YT-Videos or so. The Video is added for like 2-3 seconds and disappears afterwards. After closing the app, I was able to see that there are conversion-errors from the converter.

any idea on this? I can also provide Screenshots if needed :-)

**Comment by vicwomg** [comment]
Sorry for not clarifying. By "legacy Buster" I mean the older version of Raspberry Pi OS that runs Debian Buster, not Debian Bullseye, which is the latest version that Raspberry Pi wants you to download.

Go here
https://www.raspberrypi.com/software/operating-systems/
And scroll down to: "A stable legacy version of Raspberry Pi OS Buster." And flash that version of the OS

It is more compatible with running vlc from the command line

**Comment by Romeo1984** [comment]
@vicwomg Lite version works?

**Comment by dev03SS** [comment]
Same issue for me on Rpi 4 8 gig.

**Comment by vicwomg** [comment]
vlc/pygame removed in Pikaraoke 1.2, and along with that all installation woes.

No image, but install is very straightforward from a fresh raspberry pi os image, follow the readme
