### ISSUE TITLE
Latest image doesn't start video

### ISSUE THREAD

**Issue by takosalad** [vicwomg/pikaraoke#202]
(Image 1.1.2: https://github.com/vicwomg/pikaraoke/releases/tag/1.1.2, Pi4 4GB)
Phone interface will claim that a song is already playing, but the pi-attached monitor (or tv) will still show the qr-code-welcome screen (the "splash screen") instead of the karaoke video. Also, no sound will be output, neither via hdmi or jack.

Edit:
I updated all packages and the raspi-config tool and restarted. No change.
It does say on the splash screen "upcoming song: ..." at least, just still no actual video/sound happening.

So I tried running it from the console via sudo python3 app.py with these two commandline arguments:
I tried --use-vlc, which would result in some dbus errors and DISPLAY / X11 not being set or something (not an expert here).
I tried --use-omxplayer, which would actually play music! But still no video. :(

**Comment by vicwomg** [comment]
Sounds like something that could happen if plugged into the wrong HDMI port. 

Should be HDMI0 (the one closest to the power jack).

**Comment by takosalad** [comment]
Ohhh that was it! Thanks.

**Comment by bingobob** [comment]
I've got this happening but I'm plugged in to HDMI ok. the one nearest the power port ! any ideas?
