### ISSUE TITLE
cant search

### ISSUE THREAD

**Issue by elusus** [vicwomg/pikaraoke#21]
Anyone having an issue where it wont let you search anything? If i type in a search term. The page just refreshes and no search results come up. 

The logs shows 'Searching YouTube for: Yellow'

And it just ends there.

I'm able to launch the browser and surf the net if i close out the app. Not sure what I'm doing wrong :(

**Comment by vicwomg** [comment]
yikes, I'm seeing it too. I think Youtube might have changed something which broke search.

**Comment by vicwomg** [comment]
yes, looks like 2 days ago or so, YouTube rolled out a new version that will no longer work with how pikaraoke was scraping the search results. youtube-scrape seems to have solved it, I'll see if I can port over their solution: https://github.com/HermanFassett/youtube-scrape

**Comment by vicwomg** [comment]
The new html that YouTube sends is pretty hairy to parse. It's really complex json inside of a script tag.

youtube-scrape was on top of this change, already fixed it, and has their own heroku-based search API endpoint. I don't know if it's reliable, but calling it directly works great... for now.

Try the latest pull and let me know if it works.

**Comment by elusus** [comment]
Nice! Working for me.

**Comment by elusus** [comment]
Was able to add 5 songs until it started crapping out on me with "Internal Server Error"

Definitely awesome when it works tho.

**Comment by vicwomg** [comment]
I can't reproduce that, can you be more specific? Any specific steps and error output from the console would be great

**Comment by elusus** [comment]
I just tried it again. It's working now! I queued up about 15 songs. It was getting internal server error this morning, I swear!

**Comment by vicwomg** [comment]
if you see it again, let me know. I think certain unicode-heavy search terms throw the error, which was mostly addressed in: #19, but it's possible I'm missing something.
