### ISSUE TITLE
Feature Request: Reduce OLED screen burn ins - moving QR, IP and Logo when idle.

### ISSUE THREAD

**Issue by bobodapopper** [vicwomg/pikaraoke#211]
I think this will be a significant help for those with OLED TVs.  Having the QR and IP address moving every 5-10 seconds from corner to corner will greatly reduce, it not eliminating, the possibility of "burn ins".  I'm not sure what you can do about the "PiKaraoke" logo but if you can get that moving around the screen that would be helpful as well.  Thank you for the consideration!

**Comment by vicwomg** [comment]
The forthcoming pikaraoke version will port video playback to HTML5, so we'll get more flexibility with UI. Pygame is pretty difficult to work with.

Might be fun to do something like a spin on the classic "bouncing DVD logo" 
https://codepen.io/RobotWizard/pen/rRVKVa

**Comment by vicwomg** [comment]
Screensaver added in latest Pikaraoke 1.2
