### ISSUE TITLE
audio options with vlc?

### ISSUE THREAD

**Issue by monteslu** [vicwomg/pikaraoke#212]
On a pi4.

Audio is bad when using vlc player, but with omxplayer and `--adev local` audio is good through the headphone jack.
Problem is that omxplayer doesn't seem to be playing the cdg files.  Tried both HDMI ports.
omxplayer seems ok with mp4 from youtube on both audio and video.

Is there any way to get vlc to also use `--adev local` ?

**Comment by vicwomg** [comment]
This is no longer an issue in the latest pikaraoke 1.3, which no longer uses vlc

**Comment by monteslu** [comment]
this is awesome!  Thanks, @vicwomg 
Is there a new release planned, or should i just update my pi to the main branch?

**Comment by vicwomg** [comment]
> this is awesome! Thanks, @vicwomg Is there a new release planned, or should i just update my pi to the main branch?

You should update/pull from the main branch. However, note that 1.2 requires a desktop and browser, so if you're running a pi with Raspbian Lite, you might want to get the latest pi os desktop image.
