### ISSUE TITLE
I get no audio

### ISSUE THREAD

**Issue by lvmasterrj** [vicwomg/pikaraoke#219]
First I want to congratulate for the system and apologise by my english.

What's going on it's a bit odd, because I installed Pikaraoke and it runs normal, except for the audio. I enter a song, download it from youtube and when it plays, the video is shown but there's no sound.

If I open the file directly from the songs folder, the VLC opens normally with video and audio.

Any thoughts on what I can do?

Im running pikaraoke from a Raspberry Pi 3 B+ wih bullseye.

**Comment by vicwomg** [comment]
There are some troubleshooting steps in the README. 

If that doesn't help I'd recommend trying a buster install. VLC does not work well with bullseye on the command line

**Comment by vicwomg** [comment]
You can also try this: https://github.com/vicwomg/pikaraoke/issues/161#issuecomment-997314046

**Comment by lvmasterrj** [comment]
Thanks.

I installed the Pre-built image and now it's working fine.
