### ISSUE TITLE
High Quality Video Option

### ISSUE THREAD

**Issue by cameronwilliams** [vicwomg/pikaraoke#22]
The ability to choose to download higher quality video would be great. Maybe a checkbox? The default works perfectly for karaoke files, but it would be great to be able to choose best available quality for sing-along music videos.

**Comment by cameronwilliams** [comment]
After looking into myself, probably a bigger request than I realized. The high quality stuff usually needs to be converted which would require ffmeg meaning another app to install and update. Might not be worth it.

**Comment by vicwomg** [comment]
thanks for looking into it, was hoping it was just a simple parameter to youtube-dl. I'll keep the ticket open for now in case I or others have time to investigate this

**Comment by cameronwilliams** [comment]
On the youtube-dl side it’s fairly easy. Rather than the -f mp4, you set it to best quality and output mp4: -f bestvideo+bestaudio --merge-output-format mp4

But doing so requires ffmpeg, and I don’t know how hard it is to ensure that’s running with sufficient codec support.

**Comment by tommhendrick** [comment]
#25 This works for me. I've done about 100 songs so far and have had 0 issues. Give it a test.

**Comment by vicwomg** [comment]
we now have an --high-quality option. Not sure if it actually does anything. Simply passes in the argument "-f best" instead of "-f mp4" which may or may not do the right thing. If someone could find the secret sauce of command line options to download HD, let me know. The one in #25 did not work for me (did not merge files).

**Comment by vicwomg** [comment]
from comment in pr #25 

just checked. it uses FFMPEG to combine them. however on my rpi3 b+ I never manually installed it so maybe it came with something. So I guess the solution to hd video and audio is to include ffmpeg in the install script if you truly want HD. and then use my line above.

-best will only find the best single file which usually isn't HD.
