### ISSUE TITLE
How do I specify admin password on Raspberry Pi image?

### ISSUE THREAD

**Issue by mhcgolds** [vicwomg/pikaraoke#228]
I have tried rpi image and works like a charm. But when I turn rpi on, pikaraoke starts with the system, and it's no clear to me how to I set the admin password so it boots up with the password set.

**Comment by Hartebee5t** [comment]
If you quit out of the app I *think* there's a command you can insert into the rc.local file (ahead of the line containg the pikaraoke launch command ) to set it. When you re-boot the system performs the rc.local commands. You only need to perform this edit once, but take care to get it right in case it messes up your start-up sequence.
Also, you'd almost certainly need to precede your chosen editor's own launch command with 'sudo' to establish sufficient privilege to be able to save the edited rc.local from it.
Best of luck, and Happy New Year!

**Comment by vicwomg** [comment]
@Hartebee5t  is right, just log in to your pi (you can connect a keyboard/monitor or SSH in)

Edit the file `/etc/rc.local` and find the pikaraoke launch command and add this to it:

`--admin-password <YOUR_ADMIN_PASSWORD>`
