### ISSUE TITLE
Option to play regular video in queue

### ISSUE THREAD

**Issue by Rwestrem** [vicwomg/pikaraoke#24]
Loving this app.  An awsome option would be to also have another drop down to add regular videos and keep them kinda separated and add them in on the queue as well.  Kinda how bars do it where they throw a few videos in between singers.

**Comment by vicwomg** [comment]
I'll consider this if there's enough interest, but I don't know about encouraging copyrighted music video storage/playback.

Also, in the bars I've been to, the rule is the KJ has to sing until someone else does 😂

**Comment by petemarvin** [comment]
Maybe we can add an option to play regular videos but not download it,  just stream it using VLC.
