### ISSUE TITLE
errno premission denied

### ISSUE THREAD

**Issue by batgirldee** [vicwomg/pikaraoke#240]
every time i try and run the app.py i get permissinError: [errno 13] 13 permisson denied No mater what ive tried so far so any help would be great
its seems to relateed to crating download path;/user/lib/pikaraoke/songs

**Comment by vicwomg** [comment]
are you running as sudo? `sudo python app.py`

Also, please use the discussions section for technical support.

**Comment by batgirldee** [comment]
Yeah managed to solve it
