### ISSUE TITLE
problems with yt-dlp in pikaraoke

### ISSUE THREAD

**Issue by AaronMeyers** [vicwomg/pikaraoke#244]
I've been having an issue with yt-dlp and pikaraoke lately. what's strange is that when i try using yt-dlp by itself to download a youtube, it works fine.

here is the output of the terminal for a video i just tried to download and queue in pikaraoke:

`[2023-03-21 14:49:19] INFO: Downloading video: https://www.youtube.com/watch?v=AOkux6mojBM
[youtube] AOkux6mojBM: Downloading webpage
[youtube] AOkux6mojBM: Downloading android player API JSON
[youtube] AOkux6mojBM: Downloading player c64a5d56
WARNING: [youtube] AOkux6mojBM: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = 6pIl3SIA_tdQR51nMDcw ; player = https://www.youtube.com/s/player/c64a5d56/player_ias.vflset/en_US/base.js
ERROR: [youtube] AOkux6mojBM: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-03-21 14:49:21] ERROR: Error code while downloading, retrying once...
[youtube] AOkux6mojBM: Downloading webpage
[youtube] AOkux6mojBM: Downloading android player API JSON
WARNING: [youtube] AOkux6mojBM: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = _MZbky2zvoIEibx2tffQ ; player = https://www.youtube.com/s/player/c64a5d56/player_ias.vflset/en_US/base.js
ERROR: [youtube] AOkux6mojBM: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[2023-03-21 14:49:22] ERROR: Error downloading song: https://www.youtube.com/watch?v=AOkux6mojBM`

I tried to download the same video in another terminal window, it worked without any problems.

Any idea what's going on here?

**Comment by vicwomg** [comment]
My guess is your pikaraoke yt-dlp version is outdated, and you have another one installed that's up to date and when you're testing via CLI, it's picking the latter. There is a known bug with upgradeing yt-dlp right now  #238 See the ticket for some suggestions, you might want to see if manually upgrading it will help

**Comment by AaronMeyers** [comment]
Hmmm... in a terminal window, if I type "yt-dlp -U", it tells me I've already got the latest version.

If I try "pip3 install --upgrade yt-dlp", this is the output:
`Requirement already satisfied: yt-dlp in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (2023.3.4)
Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from yt-dlp) (2022.9.24)
Requirement already satisfied: brotli in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from yt-dlp) (1.0.9)
Requirement already satisfied: pycryptodomex in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from yt-dlp) (3.15.0)
Requirement already satisfied: mutagen in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from yt-dlp) (1.46.0)
Requirement already satisfied: websockets in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from yt-dlp) (10.3)`

If I try to update from the Web UI of pikaraoke, this is the output in the terminal:

`[2023-03-21 15:20:01] INFO: Upgrading youtube-dl, current version: 2022.10.04
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
Exception in thread Thread-13 (update_youtube_dl):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/aaron/pikaraoke/app.py", line 514, in update_youtube_dl
    k.upgrade_youtubedl()
  File "/Users/aaron/pikaraoke/karaoke.py", line 237, in upgrade_youtubedl
    output = check_output([self.youtubedl_path, "-U"]).decode("utf8").strip()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/yt-dlp', '-U']' returned non-zero exit status 1.`


Not sure why it says "Upgrading youtube-dl" there, but maybe that has something to do with it? I'm running from the latest commit of pikaraoke on the main branch...

**Comment by AaronMeyers** [comment]
ok... was looking at the README again and saw this:
`sudo ln -s `which yt-dlp` /usr/local/bin/yt-dlp`

which I tried running and it said "file exists" so I went into the /usr/local/bin/ directory, and the yt-dlp binary in there was dated October 2022 so I figured it had to be old. I deleted it, ran the symbolic link thing and I just successfully downloaded a video with pikaraoke so I think that solved it!?

**Comment by vicwomg** [comment]
tracking in #238
