### ISSUE TITLE
Changing pitch crash the program after a few tryes

### ISSUE THREAD

**Issue by lvmasterrj** [vicwomg/pikaraoke#257]
I was playing with the pitch change and then, after a few tries the home screen on my phone shows as is there was nothing playing but the song stills go on.

I was using pikaraoke on a rPi 3B+

Keep up the good work man.

Many thanks.

**Comment by vicwomg** [comment]
Was not able to reproduce this in the latest, please re-open if you can find steps to reliably reproduce this issue
