### ISSUE TITLE
Can't download or add songs

### ISSUE THREAD

**Issue by ChronoWerX82** [vicwomg/pikaraoke#264]
youtube-dl is from 2022.04.08, after update the same. it downloaded nothing

Ok, I think add manuell ... but where I put the files?

The command "pyhton app.py --help" doesn't work

> python app.py --help
Traceback (most recent call last):
  File "app.py", line 13, in <module>
    import cherrypy
ImportError: No module named cherrypy

System is a Pi 3

**Comment by vicwomg** [comment]
The latest pikaraoke should fix this.

Git pull from the pikaraoke directory, restart then try to run the YouTube
updater again. It should work better

**Comment by ChronoWerX82** [comment]
Hi, thanks.

Done, but the YouTube version is still 2022.04.08 

After update and 5 minutes wait, same version.

python app.py --help has the same error then before updating

**Comment by vicwomg** [comment]
If you're using the pre-built pikaraoke image you need to edit the auto-launch command in `/etc/rc.local` for your changes to take effect.
