### ISSUE TITLE
UnicodeEncodeErro in /templates/files.html

### ISSUE THREAD

**Issue by acamposxp** [vicwomg/pikaraoke#269]
File "/root/pikaraoke/templates/files.html", line 129, in block 'content'
    href="{{url_for('enqueue')}}?song={{url_escape(song.encode('utf-8'))}}&user="><i class="icon icon-list-add"></i> </a>
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcea' in position 69: surrogates not allowed

![Capturar](https://github.com/vicwomg/pikaraoke/assets/1779512/cfe5aa6d-885e-4567-b6c7-0a437d3887b9)

**Comment by vicwomg** [comment]
It looks like one of your files has a character that cannot be processed into utf-8 , particularly the character `\udcea`  I can't find much on that character, but it might be an emoji. You might be able to fix this by finding that file and renaming it. But I'm not sure how it could have gotten into your library. If you can share the expected file that could be useful.

**Comment by vicwomg** [comment]
I believe that adding `song.encode('utf-8','surrogateescape')` should fix this. It is currently merged to main
