### ISSUE TITLE
Overwrite Same Edited Filename

### ISSUE THREAD

**Issue by petemarvin** [vicwomg/pikaraoke#27]
I have tried to edit a song with the same "title - artist"  filename, it seems it is overwriting the existing file. I'm trying to pull a request to at least allow the same "title - artist" filename but having an index (i.e. "title - artist (2)") filename.

**Comment by vicwomg** [comment]
Yeah, that sounds like it could lead to some unexpected overwriting. 

A simple warning alert about overwriting the existing file might be best practice. Up to the user how they want to proceed with renaming.

**Comment by petemarvin** [comment]
Made #35  pull request to give the user warning if filename exist.
