### ISSUE TITLE
Windows Install "impossible" with current requirements.txt but [solved]

### ISSUE THREAD

**Issue by atcw** [vicwomg/pikaraoke#276]
I had some trouble installing the dependencies on windows with a recent python version 
but I solved it by changing the requirements.txt as follows and got it working

CherryPy
Remove version -- the version gives "uses module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?" because this got removed 

pygame; sys_platform == 'win32'
remove version so we get a pygame from a wheel and don't have to bother installing MS-devtools which I did but it still would not compile

futures
removed as it is already default nowadays.

hope this helps

**Comment by vicwomg** [comment]
This is no longer an issue in the latest pikaraoke 1.3, which removed the pygame dependency
