### ISSUE TITLE
IP Address won't work on Phone

### ISSUE THREAD

**Issue by MONKE121** [vicwomg/pikaraoke#280]
Please help IP Address won't work on phone it keeps saying " This site can't be reached"

**Comment by vicwomg** [comment]
Your phone needs to be on the same wifi network. Please do not post tech support in the issues tracker. Do it in the discussions section

**Comment by MONKE121** [comment]
It's on the same wifi network sir, I don't think the problem is on wifi, but the configuration on my network I don't have any knowlodge about it, Please help me .

Lets talk on discord or telegram.

Discord: monke9450
telegram:https://t.me/iELD1
