### ISSUE TITLE
Windows: --show-overlay Not Working

### ISSUE THREAD

**Issue by mathieugoodman** [vicwomg/pikaraoke#283]
When running in Windows, --show-overlay causes VLC to open without displaying any video. Removing the --show-overlay parameter solves the problem.

I ran the following command in Powershell to start pikaraoke: python E:\pikaraoke-1.1.2\app.py --admin-password xxxxxx --show-overlay

Edition	Windows 11 Home
Version	22H2
OS build	22621.2861
Experience	Windows Feature Experience Pack 1000.22681.1000.0

python version:
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32

yt-dlp:
[debug] Command-line config: ['-v']
[debug] Portable config "C:\Users\mathi\scoop\apps\yt-dlp\current\yt-dlp.conf": []
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1-full_build-www.gyan.dev (setts), ffprobe 6.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors

The --show-overlay option works properly on my RPi 3B+. The issue is just on Windows.

Thank you for your awesome app!

**Comment by vicwomg** [comment]
This is no longer an issue in the latest pikaraoke 1.3, which renders overlay and player in html
