### ISSUE TITLE
[BUG] -d and -y options don't work with paths that have spaces in them

### ISSUE THREAD

**Issue by RecursiveFunctions** [vicwomg/pikaraoke#287]
this screencap shows the issue with only -d , but it's the same as with -y
![issue_screencap](https://github.com/vicwomg/pikaraoke/assets/3803876/01304947-3440-4465-8107-97822171d5e6)

I tried with quotes and escaping the space but the path handling for both options does not work with paths that have spaces in the name.

 - OS: Raspberry Pi OS
 - OS version: Raspberry pi Debian Bookworm 64-bit
 - Hardware: Raspberry Pi 4 (8GB)

**Comment by vicwomg** [comment]
Not to self/whoever wants to take this on: Looks like there's some additional handling for python argparse required to parse spaces:

https://stackoverflow.com/a/26990349/2909171

**Comment by vicwomg** [comment]
This should be fixed in  the latest pull of this branch
`277-html_ffmpeg_video_rendering`

lmk if it works out

**Comment by vicwomg** [comment]
merged this to main as 1.3
