### ISSUE TITLE
[BUG] - Updating yt-dlp does not succeed

### ISSUE THREAD

**Issue by Prindle19** [vicwomg/pikaraoke#288]
**Describe the bug**
Running from the pre-built image, following the instructions to update yt-dlp via the interface is not successful. 

While tailing the log during the upgrade attempt, I see: 

[2023-12-22 07:58:47] INFO: Upgrading youtube-dl, current version: 2022.04.08
ERROR: It looks like you installed yt-dlp with a package manager, pip or setup.py; Use that to update
[2023-12-22 07:58:50] INFO: Latest version: 2023.11.16, Current version: 2022.04.08
[2023-12-22 07:58:51] INFO: Done. New version: 2022.04.08

**To Reproduce**
1. Go to 'pikaraoke GUI menu and attempt to update yt-dlp

**Expected behavior**
yt-dlp should be updated

**Platform (please complete the following information):**
Raspberry Pi 3B - latest pikaraoke 1.1.2 image. 

**Additional context**

I was able to run:

pip3 install --upgrade yt-dlp

from the terminal and upgrade at the system level and then was able to successfully download outside of pikaraoke.

yt-dlp -U presents: 

Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details. You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)

However, even after a system restart, pikaraoke GUI is still showing:

Youtube-dl (yt-dlp) version: 2022.04.08

**Comment by Prindle19** [comment]
Additional note. 

the /pikaraoke/karaoke.py file states

youtubedl_path="/usr/local/bin/yt-dlp" but running 

 /usr/local/bin/yt-dlp -U states: 
Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details. You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)

So it looks like that is up to date. 

Running 
which yt-dlp produces a different path: 

/home/pi/.local/bin/yt-dlp

**Comment by Prindle19** [comment]
Guessing this was a python environment issue. 

Fixed by manually running: 

**sudo** pip3 install --upgrade yt-dlp

**Comment by vicwomg** [comment]
I think the latest pull of pikaraoke (newer than the image) fixes this, not sure if you updated that first.

**Comment by vicwomg** [comment]
This is no longer an issue in the latest pikaraoke 1.3, which uses venv for yt-dlp management
