### ISSUE TITLE
Overlay problem in omxplayer? (and workaround)

### ISSUE THREAD

**Issue by Hartebee5t** [vicwomg/pikaraoke#3]
Hi vic...

When installing the rep on a new RPi 4 last week I found that a fairly recent update to omxplayer appears to have broken queue playback in pikaraoke (error scenario virtually identical to : (https://github.com/popcornmix/omxplayer/issues/736) ). 

Search, selection and queue management functionality still works, but the queue aborts each song as soon as it attempts to load for display, selecting instead the next song in the queue, aborting each one until the queue has been exhausted.

I discovered that I'm able to run pikaraoke if the --hide-overlay and --hide-ip CLI options are invoked. This has the effect of removing the display of the QRCode graphic and the IP address:port combo in the splash screen (but somehow the display of the title of the next song along the bottom of the splash screen is unaffected)

Regards
Hartebee5t

**Comment by vicwomg** [comment]
Thanks for the report. Does it work if you just use --hide-overlay (remove --hide-ip)? That would at least bring back the QR code.

**Comment by Hartebee5t** [comment]
Yes, hiding only the overlay works today (but I'm sure I had tried that before and it didn't work then...). Maybe I've tweaked something else since.

**Comment by Hartebee5t** [comment]
Wow! Impressive service vicwomg! Who are you, Santa Claus?
‘Tis a Christmas miracle!!

All the compliments of the season, and thank you for an awesome little application.

**Comment by vicwomg** [comment]
Let's just say Xmas at home is pretty boring :)

I didn't really solve the issue. That's up to omxplayer. But by default overlays are off now. It's a non-critical feature. If you have an older device and you want the ip and song title to show up during track playback, you can add the --show-overlay argument
