### ISSUE TITLE
mp3+cdg Not working with 303-proxy_http_ffmpeg

### ISSUE THREAD

**Issue by redmeneses** [vicwomg/pikaraoke#307]
The execution of mp3+cdg on the Master Branch works perfectly, but on the 303-proxy_http_ffmpeg_streams Branch, returns the attached errors.
log: https://1drv.ms/t/s!AhNPU2w9-qUyhPIs5rCKsjd_sbUzlw?e=x9XU77
music: https://1drv.ms/u/s!AhNPU2w9-qUyhPIr0D4xvHrAql7iSA?e=xp8t19

**Comment by vicwomg** [comment]
Thank you for the log, it's helpful. Oddly, I cannot reproduce the issue with the same file on my OSX setup. Can you tell me more about your hardware/os configuration?

"InvalidChunkLength" could indicate that the proxied response is badly formatted somehow. I can do some digging on that

**Comment by redmeneses** [comment]
I tested on various VMs, LXC Dockers, and now on a RPi4. Unfortunately, it doesn’t work for me…
log RPi4: https://1drv.ms/t/s!AhNPU2w9-qUyhPIu_dj-0jOjDNYdsQ?e=Fizk2Q

**Comment by vicwomg** [comment]
This download directory you're using, is it mounted externally? Have you tried with the default ~/pikaraoke directory? 

Obviously both should work, but that should help me narrow it down.

**Comment by redmeneses** [comment]
Including with the file saved locally, the error occurs: https://1drv.ms/t/s!AhNPU2w9-qUyhPIvk9i_RyYvwDcUpg?e=n1TFh4

**Comment by redmeneses** [comment]
In this solution from nathanpalmer nathanpalmer:proxy-url everything works correctly, including with cloudflare/zerotrust.

**Comment by vicwomg** [comment]
well the "good" news is I can reproduce this issue now, but only if I access an internet-deployed instance of pikaraoke. Running locally there doesn't seem to be an issue.

The issue occurs with **all** transcoded files (mp3 + cdg are transcoded on the fly by ffmpeg, but so are other formats like avi and mkv). Something about ffmpeg transcoding might be mangling the headers. Have not yet found a workaround, but there must be a way to do this right.

When you say you're using nathanpalmer:proxy-url, that means your setting up a separate URL for ffmpeg streams? Can you walk me through how you have that configured

The goal is to not have to do this, ideally pikaraoke handles all the proxying for you.

**Comment by vicwomg** [comment]
> So does this still happen? The proxied FFMPEG creates issues through internet deployed URLs?

Yes, as far as I know. Have not had time to investigate why the proxy isn't working properly. Probably involves some advanced networking concepts I don't have a grasp on.

**Comment by vicwomg** [comment]
This is working in #447 where we're taking a different proxying approach
