### ISSUE TITLE
[QUESTION] pikaraoke functionality

### ISSUE THREAD

**Issue by sensboston** [vicwomg/pikaraoke#315]
Unfortunately there is no attached discussion forum, so I have to use "issue" to ask the question.

I'm working on a karaoke system for Windows (I have a bunch of different RPs at home but my main "media player" (connected to a large living room TV) is a Windows PC (small, fanless but powerful, also used as a home server with a bunch of services etc.), so I am interested in any implementation of a karaoke system, multi-platform or only for Windows.

So my question is: is **pikaraoke** just a karaoke player and requires specially prepared songs (or just plays karaoke style videos from YouTube) or can it play karaoke from any mp3 file (i.e. perform vocal and instrument separation, extract text by time, etc.) ?

**Comment by vicwomg** [comment]
There is a discussions section here:
https://github.com/vicwomg/pikaraoke/discussions
