### ISSUE TITLE
[BUG] When pausing a song in the first 10 seconds, it will end the song prematurely 

### ISSUE THREAD

**Issue by frankchau93** [vicwomg/pikaraoke#319]
**Describe the bug**
This happens when I queue a new song and I decide that I want to pause it immediately because maybe there's something going on or i'm not ready to sing yet. It seems like it stops the song prematurely.

**To Reproduce**
Queue up a new song
Pause immediately after video starts playing

**Expected behavior**
To stay paused and not end the song

**Additional context**
I believe it's because there's a timeout on the splash page that ends the song if this condition isn't met

 const isVideoPlaying = (video) =>
    !!(
      video.currentTime > 0 &&
      !video.paused &&
      !video.ended &&
      video.readyState > 2
    );

// handle timeout if video fails to play
          setTimeout(() => {
            if (!isVideoPlaying(video)) {
              endSong();
            }
          }, 10000);

removing the !video.paused worked for me but I'm not sure if it would cause any bugs. is there a reason why it checks for pauses as well?

**Comment by vicwomg** [comment]
Thanks for hunting down the lines of code. I think modifying `isVideoPlaying` will mess with some expected state conditions, so I will instead adjust that timeout condition to account for pause states

**Comment by vicwomg** [comment]
fixed in the latest pull of master
