### ISSUE TITLE
[FEATURE] Only allow one connection at a time to the splash page

### ISSUE THREAD

**Issue by frankchau93** [vicwomg/pikaraoke#321]
I noticed when there is a splash page currently live and if another browser decides to go to the same splash page, it messes up the current splash page since the logic in the other splash page is triggering songs to play through the queue. I'm wondering if there's a good way to improve the splash page from being messed with. Maybe with a cookie or a code?

**Comment by vicwomg** [comment]
Looked into it, and it's not really trivial to limit connections in this way. 

I think a better solution would be to simply allow multiple splash screens, but keep them in better sync. Seems like a valid use case that a user might want the splash screen to show on multiple clients.

Filed: #448
