### ISSUE TITLE
[BUG]I installed pikaraoke following your guide for the raspberry pi, mine is the pi3 B model. That being said I use raspberry OS 32bit scrap version, I have connected a USB microphone and the problem is that the audio in the pikaraoke is not captured, otherwise if I do a test with the following command
 arecord --format=S16_LE --rate=16000 | aplay --format=S16_LE --rate=16000

The audio is captured and launches do pikaraoke with the command active the audio is also captured in the pikaraoke. How can I fix this? Why doesn't pikaraoke capture audio without first starting the Groove command on the terminal. 

### ISSUE THREAD

**Issue by 22marco77** [vicwomg/pikaraoke#326]

**Comment by vicwomg** [comment]
USB mics are not recommended, see: 
https://github.com/vicwomg/pikaraoke?tab=readme-ov-file#where-do-i-plug-in-a-microphone

Also, see https://github.com/vicwomg/pikaraoke/issues/124

**Comment by 22marco77** [comment]
> USB mics are not recommended, see: 
> https://github.com/vicwomg/pikaraoke?tab=readme-ov-file#where-do-i-plug-in-a-microphone
> 
> Also, see https://github.com/vicwomg/pikaraoke/issues/124
> 

Which microphone do you recommend? I have the wireless usb one without mixer
