### ISSUE TITLE
[BUG] Setup.sh does not identify Ubuntu-based distros as Debian-based

### ISSUE THREAD

**Issue by mcavazotti** [vicwomg/pikaraoke#335]
**Describe the bug**
When running `setup.sh`, the script doesn't identify distros that are based on Ubuntu as being derived from Debian  

**To Reproduce**
1. `./setup.sh`

**Expected behavior**
Install all the dependencies using `apt-get`

**Screenshots**

**Platform (please complete the following information):**
 - Hardware: Intel i7
 - OS: PopOs
 - OS version: PopOs 64bit
 - Browser chrome
 - Version N/A

**Additional context**
Here's the update that would fix it:
```sh
if [[ $(cat /etc/os-release | grep -E ^ID\(_LIKE\)?= | grep -i 'debian\|raspbian') != "" ]]; then

```

**Comment by TekyTech** [comment]
Yes, I noticed too and that’s why the setup didn’t install ffmpeg and chromium saying that it should be installed manually because it’s not Debian

**Comment by TekyTech** [comment]
UPDATE:
If it’s helpful to anyone, I tried it on Lubuntu 24.04, Lubuntu 22.04 and LinuxLite 7. Confirmed that it doesn’t recognize Debian on those as well. 
So I had to install ffmpeg manually, chromium manually on Lubuntu and python manually on LinuxLite.
Thank you for your hard work.

**Comment by mcavazotti** [comment]
@TekyTech could you open the installation script and replace the line that checks if the OS is Debian with the code I posted above and see if it works?

If it does, I'll create a PR with that patch.

**Comment by TekyTech** [comment]
Hello @mcavazotti 
Your line itself worked but the script failed in many places. 
First it failed to install Python I did it manually 
Then it failed to install CherryPi and I installed it manually 
Then Polaroid failed to start complaining about chromium driver.

**Comment by TekyTech** [comment]
Ha silly spell check.  pikaraoke :)
And it was on LinuxLite 7.0

**Comment by vicwomg** [comment]
I'm not sure I understand this ticket. Ubuntu and Lubuntu are not Debian. Therefore, it wont run debian-specific setup code. You need to do it manually per the README. So as far as I can tell this is working as expected.

Now if you're telling me that Ubuntu can install packages via apt-get, and that these commands DO work on Ubuntu:

```
sudo apt-get update --allow-releaseinfo-change
sudo apt-get install ffmpeg -y
sudo apt-get install chromium-browser -y
sudo apt-get install chromium-chromedriver -y
```

Then we can expand the match string to include Ubuntu. But from what I'm hearing here, that is not the case.

I am not a linux expert and can't really keep up with all the intricacies of every distribution. So I'll really need some contributors closer to those distros. Test the above commands, and let me know the output of `/etc/os-release`

**Comment by vicwomg** [comment]
I went ahead and added the suggested change. Your mileage may vary with ubuntu setup.sh, but please file new issues if they arise.

https://github.com/vicwomg/pikaraoke/pull/351

**Comment by mcavazotti** [comment]
> Now if you're telling me that Ubuntu can install packages via apt-get, and that these commands DO work on Ubuntu:
> 
> ```
> sudo apt-get update --allow-releaseinfo-change
> sudo apt-get install ffmpeg -y
> sudo apt-get install chromium-browser -y
> sudo apt-get install chromium-chromedriver -y
> ```
> 

@vicwomg yes, it's possible to install packages using apt-get
