### ISSUE TITLE
[BUG] Blank white splash screen

### ISSUE THREAD

**Issue by TekyTech** [vicwomg/pikaraoke#337]
Installed pikaraoke on an older laptop with Lubuntu 24.04. 64 bit. Tried it before installing ffmpeg and chrome.  Works searching for songs and adding them but not playing yet, as expected. 

Installed ffmpeg and chrome. Started pikaraoke.sh and everything worked beautifully. Family had fun whole evening. (THANK YOU!)

Restarted the laptop for the first time after the installation. Didn’t change anything after it was working. 
**Now all I see is a blank white local screen.**  

Checked for all updates. No updates. 

Using a browser from another computer to control pikaraoke - works to search and add songs but nothing plays. All remote browsers work fine, just nothing plays. 

Tried to run setup.sh again - still the same. Just a blank white splash screen. 

Any ideas?
Thank you and hope it might help someone too.

**Comment by TekyTech** [comment]
Funny I might have solved it accidentally. 
I put Chrome icon on the desktop and noticed exclamation mark on it. 
Then I did “trust this executable” and used Chome for some unrelated browsing. 
after that pikaraoke started to work just fine again!

**Comment by TekyTech** [comment]
NOPE… spoke too soon. 
Smother restart, another white screen. 
so “trust this executable” had nothing to do with it. Must have been just a coincidence. 
BUT after I used the Chrome again after the restart and the white screen, pikaraoke works fine again. 
Although I figured out how to use it, I can’t use it headless in fully automated way on auto start.

**Comment by vicwomg** [comment]
You mentioned you configured auto-launch. Is it possible that pikaraoke is launching before your wifi/internet is active on the machine?

**Comment by TekyTech** [comment]
No, not possible, but thank you for the thought. 

1. I had the problem before I experimented with auto start on reboot and after - I disabled auto start after realizing that I can’t use it.
2. If the laptop had no internet I would not be able to use a browser on another device to successfully access pikaraoke web interface while the host screen is blank white (chrome full screen window)
3. I actually tried to manually start pikaraoke while I disabled the internet with a hardware switch. Just to test your idea. 
4. I’m not sure anymore of every combination that I tried but I think it might have started manually at least once after a restart without auto start after a reboot. But every restart after that - still white screen. 
5. I noticed that exact same blank white screen briefly shows for a fraction of a second even when pikaraoke starts successfully. It tells me that the white blank screen is a part of the process but it just gets stuck on it for some reason. 
6. Yes, I have tried to wait for a very long time. It doesn’t get “unstuck”. 
7. I think the time when it started was when I replaced your png logo file. Could be just a coincidence though. 

thank you again.

**Comment by vicwomg** [comment]
Headed mode launches via chromedriver. The reason for this is that it must dismiss the interaction warning dialog upon startup otherwise videos wont play. 

In the setup script we can see these lines for Debian-based distros for installing chromium:
  sudo apt-get install chromium-browser -y
  sudo apt-get install chromium-chromedriver -y

I am not familiar with Linux and all the various ways to install packages, but you will need to install both the latest Chromium and Chromium-chromedriver, however that's done on your distro.

**Comment by TekyTech** [comment]
SOLVED (at least this one thing but more surfaced). 

Apparently the setup.sh didn’t recognize it as Debian distro and neither installed ffmpeg nor chromium. But the message said to install ffmpeg and Chrome manually. Ok, I followed the message and installed Google Chrome. THAT was the problem!

I wiped out my laptop and reinstalled Lubuntu and pikaraoke from scratch. Then installed ffmpeg manually and chromium as suggested above and chromedriver. Which wasn’t in the message that setup showed. 

Now everything starts every time, consistently. Whether the laptop is restarted or not. And I don’t have and don’t need actual Google Chrome browser (installed from Google). Lubuntu 22.04 comes with Firefox and it’s enough for me.

But now there are other problems. One with auto start, one with headless. Would it be better to start a new thread or maybe ok to ask here?

**Comment by TekyTech** [comment]
Sorry I meant 24.04 but it’s also true on 22.04. I tried on both. Currently using 24.04.

**Comment by TekyTech** [comment]
UPDATE about LinuxLite
I had an opportunity to try it on a desktop with most current LinuxLite. 
It starts just fine, consistently every time.
I didn’t need to manually install chromium or chromium drivers because LinuxLite comes with Chrome and whatever version is already installed works with everything. 

Auto start has some problems but it’s a completely different subject.  

Also I had to install python and ffmpeg manually because the installation doesn’t recognize LinuxLite as Debian. But there’s a separate issue posted about that as well. 
Thank you again for the great work.

**Comment by vicwomg** [comment]
Symptom of #335
