### ISSUE TITLE
[BUG] Headless doesn’t work on Ubuntu/Lubuntu

### ISSUE THREAD

**Issue by TekyTech** [vicwomg/pikaraoke#338]
Finally made it work on Ubuntu/Lubuntu 24.04 and it works as intended when launched manually. 

Does not work headless though. Consistently, replicates every single time. 

1. Start headlessly (./pikaraoke.sh --headless)
2. It starts and the terminal window shows log and progress
3. Various browsers connect to the web interface just fine, on the local computer and on remote computers. 
4. Tried with /splash and without. 
5. Without /splash it “plays” (only visually, without sound) for approx 5 seconds then stops. The log in the terminal window says:
===
INFO: Playing file: /home/user/pikaraoke-songs/[song name].mp4 transposed 0 semitone
ERROR: Stream was not playable! Run with debug logging to see output. Skipping track
INFO: Song ending: [song name]
===
The lack of sound is expected without the splash but terminating after 5 seconds is not. 

6. When trying with /splash it does exactly the same with the same messages in the log in the terminal screen with the exception that there is actually sound for those first 5 seconds of the song. 

7. I tried exact same songs that are already downloaded and which play well when manually started in a headed way: ./pikaraoke.sh so I know for sure that the same software can play those songs just fine, when it’s not in the headless mode. 

Hardware: a laptop with older Intel processor. 
OS: Lubuntu 24.04 and 22.04
Browsers: all those that I tried, including Google chrome remotely on iPhone and Firefox on local laptop.

**Comment by vicwomg** [comment]
Firefox and iPhone (Chrome,Safari) are not supported. See #299 and #327

Did you try Chrome desktop version?

**Comment by TekyTech** [comment]
Thank you. Close this I guess. That explains it. I didn’t know that those browsers are not supported.

**Comment by TekyTech** [comment]
another thought though… 
Would it make sense to not even try to run it in unsupported browser? If it can’t work, show a message or something in all browsers except supported. Something as simple as “your browser is not supported”.

**Comment by vicwomg** [comment]
Yeah, agree this is not very clear at all. I'll try to add some browser detection. Ideally I can get this working... at least in Safari because I'd like to see iOS support eventually.
