### ISSUE TITLE
[FEATURE] Shut down the system from pikaraoke interface

### ISSUE THREAD

**Issue by TekyTech** [vicwomg/pikaraoke#341]
There is already a link to quit pikaraoke.

It would be great to have another one to **shut down the whole system**. 

They could be right one after another on the same page. 

It would be very helpful when the system is used for karaoke without a dedicated keyboard/mouse.

Then users wouldn’t have to do the barbaric thing just shutting the power down abruptly.

**Comment by Hartebee5t** [comment]
I'm fairly sure that this requested 'shutdown system' feature has been in the Raspberry Pi version for several years. It is literally right after the 'shutdown pikaraoke' command in the same section of the Info page.
Are you referring to the interface on another platform?

**Comment by TekyTech** [comment]
I haven’t tried it on the actual Pi but I’ve tried it on LinuxLite, Ubuntu and Lubuntu, mostly versions 22.04 and 24.04. 

In all those environments that I’ve tried it just exits the scripts and returns to the regular desktop environment but it doesn’t shut down the system. 

Although what is says, where you are referring to it, supposedly implies that it would shut down the whole system, not just pikaraoke server script:

**Shutdown**
Don't just pull the plug! Always shut down your server properly to avoid data corruption.
- Quit Pikaraoke

So what it says is exactly right. It just doesn’t do it and only quits pikaraoke. Then the use still has to do what is advised not to do - just pull the plug (if there’s no keyboard or mouse attached)

Thank you for your feedback.

**Comment by vicwomg** [comment]
Shut down does show in the menu for pi, but not other linux systems. It would just be a matter of detecting and enabling the feature for linux. 

https://github.com/vicwomg/pikaraoke/blob/48b4383d0b502ff6037115628386435b1a331764/templates/info.html#L142-L149

**Comment by vicwomg** [comment]
Fixed in https://github.com/vicwomg/pikaraoke/pull/351

**Comment by TekyTech** [comment]
Thank you. I can confirm that now it works on Ubuntu and LinuxLite beautifully. As intended.
