### ISSUE TITLE
[FEATURE] show search results in a list or as links as opposed to a drop down list

### ISSUE THREAD

**Issue by TekyTech** [vicwomg/pikaraoke#343]
I’ve enjoyed using pikaraoke at a few real-life parties and it was fun, THANK YOU. 

I observed behavior of many great people who are unfortunately computer-illiterate or very unsophisticated users. 

What transpired was that some would search for the song but wouldn’t notice that the result of the search is a drop down list where there might be many version or variations found. So they would usually just use the first one whatever shows on the top of the drop down list. They loved the idea that there are options they could select (when they discovered it). 

I’d propose to show the results of a search in a different way that would instantly show all or at least a few songs to make it obvious to unsophisticated users that there are more. Plus even for experienced users it’s easier to see a few songs right away without even extending the drop down list. And for just a few search results, chances are that the user could see all of them right away  

The options could be:
1. A list control rather than a one-line drop down list. It could still be scrollable but show at least first 3 or 5 or 10 or even 20 options. If search result returns more than the number of default lines, it can be scrollable. People would instantly see more selection and easier to pick one. 
2. Could be a radio-button list (less preferred but still an option)
3. Could show an unlimited-length list of links on the page, just click one of those links. The whole page is scrollable in the browser. 

Hope it makes sense. 
Thanks again.

**Comment by vicwomg** [comment]
Implemented nicely by @killerbytes  and merged to master

**Comment by TekyTech** [comment]
Just wanted to say a big THANK YOU. Me and the family love it how it is implemented now. 
Much appreciate everyone’s time who make it better and better.
