### ISSUE TITLE
[BUG] Chromium-browser & Chromium-driver error with new install

### ISSUE THREAD

**Issue by sezaaru** [vicwomg/pikaraoke#361]
Hi vicwomg,

I was doing testing today and I encountered problems with both Chromium-browser and driver. I tried it on debian based LinuxL MX Linux 23, Mint Linux and Ubuntu.

I tried manual installation of Chrome, Chromium and still gives me errors related. even installed dependencies of Chromium and still throwing me errors.  I tried searching the internet and tried solutions but I believe it is something in your code. Can you please take a look. this is a specific error I have in a newly installed Mint Linux.

Ign:1 http://packages.linuxmint.com wilma InRelease                 
Hit:2 http://security.ubuntu.com/ubuntu noble-security InRelease    
Hit:3 http://archive.ubuntu.com/ubuntu noble InRelease              
Hit:4 http://packages.linuxmint.com wilma Release
Hit:5 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Reading package lists... Done

*** INSTALLING REQUIRED BINARIES ***
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:6.1.1-3ubuntu5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help resolve the situation:

The following packages have unmet dependencies:
 chromium-browser : PreDepends: snapd but it is not installable
E: Unable to correct problems, you have held broken packages.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help resolve the situation:

The following packages have unmet dependencies:
 chromium-browser : PreDepends: snapd but it is not installable
E: Unable to correct problems, you have held broken packages.
ERROR: Binary dependency installation failed with error code: 0

**Comment by vicwomg** [comment]
Not sure what that error means, but looks like not all Debian OS are able to install chromium.

If you've installed Chrome manually, you can try executing the remaining setup steps manually

```
python3 -m venv .venv
source .venv/bin/activate
pip3 install -r requirements.txt
```

Then proceed with launching pikaraoke as usual. LMK if that works

**Comment by vicwomg** [comment]
Closing, the setup script is deprecated and is no longer supported
