### ISSUE TITLE
[FEATURE] Spanish Translation

### ISSUE THREAD

**Issue by leemongchupao** [vicwomg/pikaraoke#372]
I want to make a collab in this project, doing the spanish version! I already modify the .PO file with a very accurate spanish version on this project! Hope you all like it!

[link to the spanish file](https://github.com/leemongchupao/pikaraoke/blob/master/pikaraoke/translations/es_VE)

**Comment by vicwomg** [comment]
Thank you for your translation! I have added it

**Comment by leemongchupao** [comment]
I update the spanish translation including the .po next to de .mo file!
