### ISSUE TITLE
[BUG] Browse screen - Add Song Icon gets overlayed by song number when library is over 999 songs

### ISSUE THREAD

**Issue by Romeo1984** [vicwomg/pikaraoke#379]
Describe the bug
In the song browser, when files are over 999 (1000+) then the "Add Song" hyperlink graphic icon is overlapped with text. 

To Reproduce

1. Load over 999 karaoke files 
2. Go to the admin page and re-scan song directory
3. Navigate to the "Browse" Page 
4. See that the Add song icon is blended with the song number. It makes it difficult to click on when on a mobile device. 

Expected behavior
There would be ample white space between the icon to add a song and the text identifying the song. 

Screenshots
Screenshot 2024-09-01 110009.jpg
![Screenshot 2024-09-01 110009](https://github.com/user-attachments/assets/ec91b42e-58f5-4e3d-97d4-db45fb4d4fac)

Platform (please complete the following information):

Platform: Raspberry Pi 4 Model B Rev 1.5
OS Version: #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07)
Youtube-dl (yt-dlp) version: 2024.08.06
FFmpeg version: 5.1.6-0+deb12u1+rpt1
Pikaraoke version: 1.2.1

Browser: chrome Version 128.0.6613.86 (Official Build) (64-bit)

Additional context
my CDG collection consists of 87000 songs. 
This has been duplicated on the pi, windows and Apple phone browsers.

**Comment by vicwomg** [comment]
fixed in v. 1.5.0

**Comment by Romeo1984** [comment]
@vicwomg Tested and working. Thank you!
