### ISSUE TITLE
[BUG] Documentation - TROUBLESHOOTING.md for bypassing confirmation prompt is inaccurate

### ISSUE THREAD

**Issue by Romeo1984** [vicwomg/pikaraoke#380]
TROUBLESHOOTING.md Text Reads:

`How do I dismiss the Splash confirmation screen on an in-TV browser? (like a Samsung TV with web browsing)
The splash confirmation screen is an unfortunate necessity due to modern browser permissions disabling video autoplay. A single interaction will enable it, and the confirmation screen serves as this interaction. Hopefully your TV has a way to click the button on the screen with the remote or otherwise.

If you want to try without confirmation, you can add a parameter to the end of the splash screen URL "confirm=false". Ex: http://pikaraoke.local:5555/splash.html?confirm=false but there's no guarantee that videos will play; it depends on the embedded browser implementation.`

This URL generates a 404 error. The ".html" needs to be removed. 

The proper URL is:
http://pikaraoke.local:5555/splash?confirm=false

And BTW, this works on my Chromium app in Bookworm when pikaraoke ran in headless mode.

**Comment by vicwomg** [comment]
thanks! will fix that. And interesting news that chromium doesn't require interaction. I will have to explore that further
