### ISSUE TITLE
help for new install Pikaraoke 1.2

### ISSUE THREAD

**Issue by cirdec321** [vicwomg/pikaraoke#381]
hello 

i ve got the old version of Pikaraoke and all work well but yesterday I can download music.  I've erase my SD card for a new installation but I can t install the new version of the Pikaraoke (big changement)

can you help me for install that in the SD card empty (on raspberry 4) ?  sorry for my English 

there is a Img files ?  or I have to install juste a Arabian version ?

thanks you 
Cirdec

**Comment by vicwomg** [comment]
The readme explains how to install : https://github.com/vicwomg/pikaraoke

If you have trouble, open a discussion, not a issue ticket
