### ISSUE TITLE
[BUG] Release to PyPi

### ISSUE THREAD

**Issue by mariugul** [vicwomg/pikaraoke#388]
@vicwomg See [CI Release Please](https://github.com/vicwomg/pikaraoke/actions/runs/10677167844/job/29591856247#step:10:1)

Typically this means the environment "pypi" was not created on the GitHub repo or trusted publisher was not setup in PyPi.

Go to https://pypi.org/manage/account/publishing/ and verify that you added a trusted publisher:

![image](https://github.com/user-attachments/assets/88fa0b58-417e-4b76-9def-5c0f85500176)

**Comment by vicwomg** [comment]
Opened this to add some values to the pyproject.toml
https://github.com/vicwomg/pikaraoke/pull/389

But I'm not sure that will properly set the long_description. @mariugul  this guide: https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/ says we need to create a setup.py to set the long_description from readme. Is that accurate? I'm not familiar with setup.py conventions and where it should live in the project.

**Comment by mariugul** [comment]
> Got a little bit further, but now the error is:
> 
> ```
> /usr/bin/docker run --name f07bf0e7a0b4d4e5895ccf984a6d37af0_b2d177 --label 40880f --workdir /github/workspace --rm -e "pythonLocation" -e "PKG_CONFIG_PATH" -e "Python_ROOT_DIR" -e "Python2_ROOT_DIR" -e "Python3_ROOT_DIR" -e "LD_LIBRARY_PATH" -e "INPUT_USER" -e "INPUT_PASSWORD" -e "INPUT_REPOSITORY-URL" -e "INPUT_REPOSITORY_URL" -e "INPUT_PACKAGES-DIR" -e "INPUT_PACKAGES_DIR" -e "INPUT_VERIFY-METADATA" -e "INPUT_VERIFY_METADATA" -e "INPUT_SKIP-EXISTING" -e "INPUT_SKIP_EXISTING" -e "INPUT_VERBOSE" -e "INPUT_PRINT-HASH" -e "INPUT_PRINT_HASH" -e "INPUT_ATTESTATIONS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/pikaraoke/pikaraoke":"/github/workspace" 40880f:07bf0e7a0b4d4e5895ccf984a6d37af0  "__token__" "" "" "" "" "" "false" "" "false"
> Checking dist/pikaraoke-1.4.0-py3-none-any.whl: FAILED
> ERROR    `long_description` has syntax errors in markup and would not be        
>          rendered on PyPI.                                                      
>          No content rendered from RST source.                                   
> WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.   
> Checking dist/pikaraoke-1.4.0.tar.gz: PASSED with warnings
> WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.   
> WARNING  `long_description` missing.  
> ```
> 
> Maybe if I add the README it will render as the long description, but seems like there might be some additional setup to make that work properly: https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/

I agree, I think that's the solution.

**Comment by mariugul** [comment]
> Opened this to add some values to the pyproject.toml #389
> 
> But I'm not sure that will properly set the long_description. @mariugul this guide: https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/ says we need to create a setup.py to set the long_description from readme. Is that accurate? I'm not familiar with setup.py conventions and where it should live in the project.

setup.py is not necessary :smile:

**Comment by mariugul** [comment]
Adding readme solved it.

**Comment by vicwomg** [comment]
Excellent. Looks good on pypi and renders well enough.

What's your opinion on having a dedicated release candidate branch? I am
not sure I like having a release for every bugfix. It would be nice to
batch them up and merge them all together as a single PR with a nice
changelist.

**Comment by mariugul** [comment]
> Excellent. Looks good on pypi and renders well enough. What's your opinion on having a dedicated release candidate branch? I am not sure I like having a release for every bugfix. It would be nice to batch them up and merge them all together as a single PR with a nice changelist.

My opinion is that one bugfix should be one commit and that one PR should ideally be one bugfix. If that is practiced, you would have solved one bug in one commit that ends up on the production branch (main). Assuming you tested before merging, the bug is now fixed. In agile methodology and CI/CD this means it's now ready to integrate and deploy. So if that's the case, I don't see why you would like to wait to release a bugfix only to fix a few more first. That newly improved app with the fixed bug is directly ready to consume. I don't really see the benefit of waiting to release it. That's sort of what working agile means, to continously release small increments.

What you are talking about is a different strategy, which has its place. I think that sort of strategy is good for larger applications. For games as well perhaps, where you want to release batches of improvements. This can be a marketing strategy for example where a released update has some cool features or simply a security thing. Say an app for flight control cannot be updated all the time, it needs to be in controlled batches of updated where employees get training on the new updates.

So my opinion is that a small app like this benefits more from an agile workflow than to save up releasable chunks of work. That said, all releases that have minor increments should be backwards compatible. So a user of `pikaraoke` should know easily that a major change means API breaking. Therefore it shouldn't really make a difference that `pikaraoke` is released often as it doesn't (shouldn't) break anything.

**Comment by vicwomg** [comment]
Ok, certainly worth a try. Is there a way to make release please generate a github release as well? That is how I have been handling releases thus far
