### ISSUE TITLE
[BUG] pikaraoke headed mode throws errors on launch over SSH

### ISSUE THREAD

**Issue by vicwomg** [vicwomg/pikaraoke#395]
**Describe the bug**
Trying to launch pikaraoke headed mode over SSH results in a cryptic error

The solution is described here in the wiki
 https://github.com/vicwomg/pikaraoke/wiki/FAQ-&-Troubleshooting#im-getting-this-chromedriver-error-on-launch-session-not-created-devtoolsactiveport-file-doesnt-exist

But it is still biting a lot of users and causing confusion.

**To Reproduce**
1. SSH to a pi 
2. Run `pikaraoke` 
3. Error on launch: `session not created: DevToolsActivePort file doesn't exist`

**Expected behavior**
Catch this error and detect if the user is running over SSH. If so, we should output more meaningful error text and suggest prepending with DISPLAY=:0.0

**Platform (please complete the following information):**
 - Hardware: N/A

**Comment by brianroco** [comment]
I'm encountering this error too in Rpi4B running Raspbian GNU/Linux 10 (buster)
installed via `pip install pikaraoke`
Auto starting it via systemd.system
```
root@pikaraoke:~# cat /etc/systemd/system/pikaraoke.service 
[Unit]
Description=pikaraoke
After=network.target

[Service]
Environment=DISPLAY=:0.0
Environment=XAUTHORITY/home/pi/.Xauthority
WorkingDirectory=/home/pi/
ExecStart=/usr/local/bin/pikaraoke --youtubedl-path /home/pi/.local/bin/yt-dlp --download-path /usr/lib/pikaraoke/songs --volume 0.75
Environment="PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.12/site-packages/"
Restart=always

[Install]
WantedBy=multi-user.target
```
Doing `export DISPLAY=:0.0` remotely via ssh and running above ExecStart cmd results to same error
```
Oct 06 19:50:55 pikaraoke systemd[1]: Started pikaraoke.
Oct 06 19:51:29 pikaraoke pikaraoke[465]: [2024-10-06 19:51:29] INFO: Fetching available songs in: /usr/lib/pikaraoke/songs/
Oct 06 19:51:40 pikaraoke pikaraoke[465]: [2024-10-06 19:51:40] INFO: Upgrading youtube-dl, current version: 2024.09.27
Oct 06 19:51:55 pikaraoke pikaraoke[465]: [2024-10-06 19:51:55] INFO: Latest version: stable@2024.09.27 from yt-dlp/yt-dlp
Oct 06 19:51:55 pikaraoke pikaraoke[465]: yt-dlp is up to date (stable@2024.09.27 from yt-dlp/yt-dlp)
Oct 06 19:52:06 pikaraoke pikaraoke[465]: [2024-10-06 19:52:06] INFO: Done. New version: 2024.09.27
Oct 06 19:52:06 pikaraoke pikaraoke[465]: [06/Oct/2024:19:52:06] ENGINE Bus STARTING
Oct 06 19:52:06 pikaraoke pikaraoke[465]: [2024-10-06 19:52:06] INFO: [06/Oct/2024:19:52:06] ENGINE Bus STARTING
Oct 06 19:52:06 pikaraoke pikaraoke[465]: [06/Oct/2024:19:52:06] ENGINE Serving on http://0.0.0.0:5555
Oct 06 19:52:06 pikaraoke pikaraoke[465]: [2024-10-06 19:52:06] INFO: [06/Oct/2024:19:52:06] ENGINE Serving on http://0.0.0.0:5555
Oct 06 19:52:06 pikaraoke pikaraoke[465]: [06/Oct/2024:19:52:06] ENGINE Bus STARTED
Oct 06 19:52:06 pikaraoke pikaraoke[465]: [2024-10-06 19:52:06] INFO: [06/Oct/2024:19:52:06] ENGINE Bus STARTED
Oct 06 19:52:09 pikaraoke pikaraoke[465]: Traceback (most recent call last):
Oct 06 19:52:09 pikaraoke pikaraoke[465]:   File "/usr/local/bin/pikaraoke", line 8, in <module>
Oct 06 19:52:09 pikaraoke pikaraoke[465]:     sys.exit(main())
Oct 06 19:52:09 pikaraoke pikaraoke[465]:              ^^^^^^
Oct 06 19:52:09 pikaraoke pikaraoke[465]:   File "/usr/local/lib/python3.12/site-packages/pikaraoke/app.py", line 942, in main
Oct 06 19:52:09 pikaraoke pikaraoke[465]:     driver = webdriver.Chrome(service=service, options=options)
Oct 06 19:52:09 pikaraoke pikaraoke[465]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 06 19:52:09 pikaraoke pikaraoke[465]:   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
Oct 06 19:52:09 pikaraoke pikaraoke[465]:     super().__init__(
Oct 06 19:52:09 pikaraoke pikaraoke[465]:   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
Oct 06 19:52:10 pikaraoke pikaraoke[465]:     super().__init__(command_executor=executor, options=options)
Oct 06 19:52:10 pikaraoke pikaraoke[465]:   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
Oct 06 19:52:10 pikaraoke pikaraoke[465]:     self.start_session(capabilities)
Oct 06 19:52:10 pikaraoke pikaraoke[465]:   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
Oct 06 19:52:10 pikaraoke pikaraoke[465]:     response = self.execute(Command.NEW_SESSION, caps)["value"]
Oct 06 19:52:10 pikaraoke pikaraoke[465]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 06 19:52:10 pikaraoke pikaraoke[465]:   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
Oct 06 19:52:10 pikaraoke pikaraoke[465]:     self.error_handler.check_response(response)
Oct 06 19:52:10 pikaraoke pikaraoke[465]:   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
Oct 06 19:52:10 pikaraoke pikaraoke[465]:     raise exception_class(message, screen, stacktrace)
Oct 06 19:52:10 pikaraoke pikaraoke[465]: selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
Oct 06 19:52:10 pikaraoke pikaraoke[465]:   (unknown error: DevToolsActivePort file doesn't exist)
Oct 06 19:52:10 pikaraoke pikaraoke[465]:   (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Oct 06 19:52:10 pikaraoke pikaraoke[465]: Stacktrace:
```

**Comment by Romeo1984** [comment]
> I'm encountering this error too in Rpi4B running Raspbian GNU/Linux 10 (buster) installed via `pip install pikaraoke` Auto starting it via systemd.system
> 
> ```
> root@pikaraoke:~# cat /etc/systemd/system/pikaraoke.service 
> [Unit]
> Description=pikaraoke
> After=network.target
> 
> [Service]
> Environment=DISPLAY=:0.0
> Environment=XAUTHORITY/home/pi/.Xauthority
> WorkingDirectory=/home/pi/
> ExecStart=/usr/local/bin/pikaraoke --youtubedl-path /home/pi/.local/bin/yt-dlp --download-path /usr/lib/pikaraoke/songs --volume 0.75
> Environment="PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.12/site-packages/"
> Restart=always
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> Doing `export DISPLAY=:0.0` remotely via ssh and running above ExecStart cmd results to same error
> 
> ```
> Oct 06 19:50:55 pikaraoke systemd[1]: Started pikaraoke.
> Oct 06 19:51:29 pikaraoke pikaraoke[465]: [2024-10-06 19:51:29] INFO: Fetching available songs in: /usr/lib/pikaraoke/songs/
> Oct 06 19:51:40 pikaraoke pikaraoke[465]: [2024-10-06 19:51:40] INFO: Upgrading youtube-dl, current version: 2024.09.27
> Oct 06 19:51:55 pikaraoke pikaraoke[465]: [2024-10-06 19:51:55] INFO: Latest version: stable@2024.09.27 from yt-dlp/yt-dlp
> Oct 06 19:51:55 pikaraoke pikaraoke[465]: yt-dlp is up to date (stable@2024.09.27 from yt-dlp/yt-dlp)
> Oct 06 19:52:06 pikaraoke pikaraoke[465]: [2024-10-06 19:52:06] INFO: Done. New version: 2024.09.27
> Oct 06 19:52:06 pikaraoke pikaraoke[465]: [06/Oct/2024:19:52:06] ENGINE Bus STARTING
> Oct 06 19:52:06 pikaraoke pikaraoke[465]: [2024-10-06 19:52:06] INFO: [06/Oct/2024:19:52:06] ENGINE Bus STARTING
> Oct 06 19:52:06 pikaraoke pikaraoke[465]: [06/Oct/2024:19:52:06] ENGINE Serving on http://0.0.0.0:5555
> Oct 06 19:52:06 pikaraoke pikaraoke[465]: [2024-10-06 19:52:06] INFO: [06/Oct/2024:19:52:06] ENGINE Serving on http://0.0.0.0:5555
> Oct 06 19:52:06 pikaraoke pikaraoke[465]: [06/Oct/2024:19:52:06] ENGINE Bus STARTED
> Oct 06 19:52:06 pikaraoke pikaraoke[465]: [2024-10-06 19:52:06] INFO: [06/Oct/2024:19:52:06] ENGINE Bus STARTED
> Oct 06 19:52:09 pikaraoke pikaraoke[465]: Traceback (most recent call last):
> Oct 06 19:52:09 pikaraoke pikaraoke[465]:   File "/usr/local/bin/pikaraoke", line 8, in <module>
> Oct 06 19:52:09 pikaraoke pikaraoke[465]:     sys.exit(main())
> Oct 06 19:52:09 pikaraoke pikaraoke[465]:              ^^^^^^
> Oct 06 19:52:09 pikaraoke pikaraoke[465]:   File "/usr/local/lib/python3.12/site-packages/pikaraoke/app.py", line 942, in main
> Oct 06 19:52:09 pikaraoke pikaraoke[465]:     driver = webdriver.Chrome(service=service, options=options)
> Oct 06 19:52:09 pikaraoke pikaraoke[465]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Oct 06 19:52:09 pikaraoke pikaraoke[465]:   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
> Oct 06 19:52:09 pikaraoke pikaraoke[465]:     super().__init__(
> Oct 06 19:52:09 pikaraoke pikaraoke[465]:   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
> Oct 06 19:52:10 pikaraoke pikaraoke[465]:     super().__init__(command_executor=executor, options=options)
> Oct 06 19:52:10 pikaraoke pikaraoke[465]:   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
> Oct 06 19:52:10 pikaraoke pikaraoke[465]:     self.start_session(capabilities)
> Oct 06 19:52:10 pikaraoke pikaraoke[465]:   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
> Oct 06 19:52:10 pikaraoke pikaraoke[465]:     response = self.execute(Command.NEW_SESSION, caps)["value"]
> Oct 06 19:52:10 pikaraoke pikaraoke[465]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Oct 06 19:52:10 pikaraoke pikaraoke[465]:   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
> Oct 06 19:52:10 pikaraoke pikaraoke[465]:     self.error_handler.check_response(response)
> Oct 06 19:52:10 pikaraoke pikaraoke[465]:   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
> Oct 06 19:52:10 pikaraoke pikaraoke[465]:     raise exception_class(message, screen, stacktrace)
> Oct 06 19:52:10 pikaraoke pikaraoke[465]: selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
> Oct 06 19:52:10 pikaraoke pikaraoke[465]:   (unknown error: DevToolsActivePort file doesn't exist)
> Oct 06 19:52:10 pikaraoke pikaraoke[465]:   (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
> Oct 06 19:52:10 pikaraoke pikaraoke[465]: Stacktrace:
> ```

@brianroco Can I ask what is your use case for starting pikaraoke as a service? I ask because I am using it in "kiosk mode" where my pi device is built to only be a karaoke player and nothing else. I use a different pi image to accomplish this that works very well. Let me know if you are interested in trying this way.

**Comment by vicwomg** [comment]
I'm no expert in systemd, but is your XAUTHORITY env variable missing an
equals sign?

**Comment by brianroco** [comment]
@Romeo1984 My usage is also as a karaoke player and nothing more. Unfortunately, I am unable to implement any other means to autostart pikaraoke successfully, the systemd service is my last option. Can I ask how and where do you autostart the program?

@vicwomg added the missing equal sign but error is persistent.

**Comment by Romeo1984** [comment]
@brianroco check out bug #402 for my systemd file. I am using FullpageOS instead of the standard pi OS. It is a slim version and only boots into a desktop session with Chromium and nothing else. 

I am hopping on a plane this morning for work. This weekend I will post in the discussion group steps to build a kiosk for pikaraoke.

**Comment by Romeo1984** [comment]
@brianroco I posted my How To instruction for running in Kiosk Mode Here: https://github.com/vicwomg/pikaraoke/discussions/406

**Comment by brianroco** [comment]
Not seeing the chromium-browser but still errors with this
```
Oct 22 12:53:31 pikaraoke systemd[1]: Started pikaraoke.
Oct 22 12:53:39 pikaraoke python[1327]: Traceback (most recent call last):
Oct 22 12:53:39 pikaraoke python[1327]:   File "/home/pi/.venv/bin/pikaraoke", line 8, in <module>
Oct 22 12:53:39 pikaraoke python[1327]:     sys.exit(main())
Oct 22 12:53:39 pikaraoke python[1327]:              ^^^^^^
Oct 22 12:53:39 pikaraoke python[1327]:   File "/home/pi/.venv/lib/python3.12/site-packages/pikaraoke/app.py", line 890, in main
Oct 22 12:53:39 pikaraoke python[1327]:     k = karaoke.Karaoke(
Oct 22 12:53:39 pikaraoke python[1327]:         ^^^^^^^^^^^^^^^^
Oct 22 12:53:39 pikaraoke python[1327]:   File "/home/pi/.venv/lib/python3.12/site-packages/pikaraoke/karaoke.py", line 157, in __init__
Oct 22 12:53:39 pikaraoke python[1327]:     addresses_str = check_output(["hostname", "-I"]).strip().decode("utf-8", "ignore")
Oct 22 12:53:39 pikaraoke python[1327]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 22 12:53:39 pikaraoke python[1327]:   File "/usr/local/lib/python3.12/subprocess.py", line 466, in check_output
Oct 22 12:53:39 pikaraoke python[1327]:     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
Oct 22 12:53:39 pikaraoke python[1327]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 22 12:53:39 pikaraoke python[1327]:   File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
Oct 22 12:53:39 pikaraoke python[1327]:     with Popen(*popenargs, **kwargs) as process:
Oct 22 12:53:39 pikaraoke python[1327]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 22 12:53:39 pikaraoke python[1327]:   File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
Oct 22 12:53:39 pikaraoke python[1327]:     self._execute_child(args, executable, preexec_fn, close_fds,
Oct 22 12:53:39 pikaraoke python[1327]:   File "/usr/local/lib/python3.12/subprocess.py", line 1950, in _execute_child
Oct 22 12:53:39 pikaraoke python[1327]:     raise child_exception_type(errno_num, err_msg, err_filename)
Oct 22 12:53:39 pikaraoke python[1327]: FileNotFoundError: [Errno 2] No such file or directory: 'hostname'
Oct 22 12:53:40 pikaraoke systemd[1]: pikaraoke.service: Main process exited, code=exited, status=1/FAILURE
Oct 22 12:53:40 pikaraoke systemd[1]: pikaraoke.service: Failed with result 'exit-code'.
Oct 22 12:53:43 pikaraoke systemd[1]: pikaraoke.service: Service RestartSec=3s expired, scheduling restart.
Oct 22 12:53:43 pikaraoke systemd[1]: pikaraoke.service: Scheduled restart job, restart counter is at 51.
Oct 22 12:53:43 pikaraoke systemd[1]: Stopped pikaraoke.
```
I am connected via ssh, network wise i have a network.

**Comment by brianroco** [comment]
I'll try building off the image you mentioned. I was just updating my existing image where I used to ran the old version.

**Comment by brianroco** [comment]
@Romeo1984 rebuilding base OS and using your instruction works like a charm. 🙌  👍

**Comment by Romeo1984** [comment]
> @Romeo1984 rebuilding base OS and using your instruction works like a charm. 🙌 👍

Glad to hear it!

**Comment by vicwomg** [comment]
Fixed in https://github.com/vicwomg/pikaraoke/releases/tag/1.5.2
