### ISSUE TITLE
tempora requires Python '>3.6' but the running python is 2.7.16

### ISSUE THREAD

**Issue by zanshinv** [vicwomg/pikaraoke#4]
I am using a raspberry pi 4 and am coming accross two stumbling blocks 

Once I try to install the python dependancies with [sudo pip install -r requirements.txt] I get the message that
"tempora requires Python '>3.6' but the running python is 2.7.16"
I have checked the version of python and python3 running on my pi using [pyton --version] and i get python 2.7.16 and pyton 3.7.3

Continuing to follow the instructions once I try to run the app, the following error message appears:
Traceback (most recent call last):
File "app.py" , line 11 in <module>
import karaoke
File "/home/pi/Desktop/pikaraoke/karaoke.py", line 12, in <module>
import qrcode
ImportError: No module named qrcode

Thank you very much for any help that you can offer!

and thank you for an awesome project, I cant wait to get it up and running in time for christmas if you can help me with the set up

**Comment by bennysp** [comment]
I am receiving the same thing.

**Comment by bennysp** [comment]
@zanshinv I just got around this...

Run the below commands and then re-run the requirements file:

`sudo pip install --upgrade tempora==1.9.0`
`sudo pip install --upgrade jaraco.functools==2.0`

then re-run:

`sudo pip install -r requirements.txt`

**Comment by vicwomg** [comment]
Thanks so much for the report and the fix! I'll experiment with adding tempora==1.9.0 and jaraco.functools==2.0  to the requirements.txt

**Comment by zanshinv** [comment]
fantastic, thats got it booted up! thank you so much for the fix bennysp, and thank you for the awesome project vicwomg.

sorry to be a pain though, ive come into another stumbling block, the tracks are downloading fine, and no problem adding to the queue but it seems like the tracks just skipping through, i see 'up next' on the bottom of the screen for a few and then it dissapears, the splash screen never changes?

**Comment by vicwomg** [comment]
Pi 4? Try adding the following parameter to the app.py command

--hide-overlay

There is a bug in new versions of omxplayer: https://github.com/vicwomg/pikaraoke/issues/3

**Comment by zanshinv** [comment]
thats the one, im so sorry for my dumb questions ... can i ask where to add --hide overlay in the code? ive tried adding the line 
--hide-overlay 
at the beginning and end, but i get the error:
name 'hide' is not defined

**Comment by vicwomg** [comment]
No worries. Don't add it to the code itself, you add it to the launch command. Ex:

`python app.py --port 8080 --download-path /home/pi/songs --hide-overlay`

**Comment by zanshinv** [comment]
I see, thank you for your patience and explaining... ive run with --hide-overlay, and --hide-ip as mentioned in the other thread and the issue of it skipping or cancelling the tracks as soon as they begin appears to be solved - the track names appear on the screen and appear to stay on 'now playing' for the duration of the song, however I am still not getting any video, sound or lyrics appearing - just the splash screen

**Comment by vicwomg** [comment]
I'd leave out --hide-ip. That will hide the QR code from the splash, which you probably don't want.

I can offer some more troubleshooting steps, but you're going to need to run commands on the command line. 

Did you add the "gpu_mem=128" to /boot/config.txt as stated in the installation guide? 

Make sure your system is up to date:
`sudo apt-get update
sudo apt-get upgrade
sudo reboot`

try opening a file manually:
`/usr/bin/omxplayer <replace_with_path_to_downloaded_song_file>`

If that doesn't work, post the output of what it says. If it does work... then I really think I'm getting to the point where it's going to be very hard to troubleshoot this without having this setup in front of me

**Comment by zanshinv** [comment]
I really appreciate your help with this, 

the system is up to date and i have added gpu_mem=128 to /boot/config.txt

opening the file manually seems a bit tricky using the command line - as all the track names have spaces in them i get the error 
file <path to song file but only the first word> not found.

ill go ahead and format the card and try again in the morning, whether it works or not i am grateful for you taking the time to troubleshoot it with me so far and i understand it may not be something that you can solve without the setup in front of you, ill post here to let you know either way.

**Comment by vicwomg** [comment]
Ah, well in linux systems, spaces need to be "escaped" by preceeding them with a backslash. So: "01 - song 1.mp4" would need to be "01\ song\ 1.mp4"

But in a bash shell (which I assume you're using if raspbian), the trick is never type out the full name of a file, just use tab completion. As you begin typing out the first few characters of the path to the file, press the tab key and it will auto-fill the rest, escaping all the spaces with a backslash automatically.

I feel like we're getting beyond the scope of this particular bug ticket.

**Comment by vicwomg** [comment]
fixed with versioning and with the new ./setup.sh script
