### ISSUE TITLE
Song Preview

### ISSUE THREAD

**Issue by petemarvin** [vicwomg/pikaraoke#40]
Hi @vicwomg Im not really familiar with cherrypi.  Is it possible that the mp4 files can be access through http?

What I wanted to achieve is to be able play/preview the karaoke songs via http (clients phone)  and possibly create a basic trim video function using ffmpeg.

**Comment by vicwomg** [comment]
cherrypi should support anything a standard http server does, but technically, the web framework is Flask on this project. I've thought about allowing streaming to phone too, that way users could use their phones as a handheld karaoke machine. I think you'd just need to figure out how to convert the file path to an http endpoint in Flask.

**Comment by petemarvin** [comment]
Thanks @vicwomg was able to access the files already based on your suggestion.
```
@app.route('/files/<path:filename>', methods=['GET', 'POST'])
def stream(filename):
    return send_from_directory(directory=k.download_path, filename=filename)
```
Can be accessed using http://192.168.1.12:5000/files/Hello%20-%20Lionel%20Richie.mp4

**Comment by vicwomg** [comment]
This is not really a ticket, more of a question. Closing for now. If you want to implement it as some kind of feature, define it as such in a new ticket
