### ISSUE TITLE
[BUG] ADMIN MODE not working on v1.5.1

### ISSUE THREAD

**Issue by bdmarinho** [vicwomg/pikaraoke#401]
**Describe the bug**
ADMIN MODE not working on v1.5.1. 
I am using the same command line that was working for v1.2.

**To Reproduce**
Running pikaraoke --admin-password admin

**Expected behavior**
Shows the Log In or Log Out option for locking/unlocking features

**Screenshots**
![image](https://github.com/user-attachments/assets/2e3ab0dc-19f4-48f0-b6b1-1d2960b1927d)
![image](https://github.com/user-attachments/assets/addcd4f6-7ae0-443a-a0ba-a5c7b2bff95a)

**Platform (please complete the following information):**
 - Hardware: Windows PC
 - OS: Windows 10
 - OS version: 10.0.19045
 - Browser: Chrome
 - Version: 1.5.1

**Additional context**
Thanks for this amazing solution!!!

**Comment by andreijoda** [comment]
Mine has the same problem, has it been resolved?

**Comment by jepes1981** [comment]
declaring admin_password globally resolved this issue for me. The bug was admin_password defaults to None because it goes out of scope after assignment of args.admin_password.

`    args = parser.parse_args()

    if args.admin_password:
        global admin_password    // declare admin_password as global variable
        admin_password = args.admin_password`

**Comment by vicwomg** [comment]
> declaring admin_password globally resolved this issue for me. The bug was admin_password defaults to None because it goes out of scope after assignment of args.admin_password.
> 
> ` args = parser.parse_args()
> 
> ```
> if args.admin_password:
>     global admin_password    // declare admin_password as global variable
>     admin_password = args.admin_password`
> ```

Bingo, that's the fix. Appreciate it. I will get that pushed out.
