### ISSUE TITLE
[BUG] Transposing hangs when ffmpeg does not have librubberband

### ISSUE THREAD

**Issue by vicwomg** [vicwomg/pikaraoke#427]
**Describe the bug**
If ffmpeg doesn't include `enable-librubberband`, then transposition doesn't work, and it will hang the app.

**To Reproduce**
Use pikaraoke on any machine with a version of ffmpeg lacking in librubberband. You can check by running `ffmpeg` on the command line and noting the absense of "--enable-librubberband" in the output under "configuration:"

Most recent versions of ffmpeg include librubberband, but we recently found that Android + termux ffmpeg 6.1 package doesn't

**Expected behavior**
Pikaraoke should warn the user in logging and disable the transposition feature.

**Platform (please complete the following information):**
 - Hardware: Android
 - OS: Android OS / Termux linux runtime
 - OS version:  8.0
 - Browser: N/A
 - Version: N/A

**Comment by vicwomg** [comment]
I think the feature should just be hidden. If we want to display a message, I think it should be under the pikaraoke info page next to the ffmpeg version

<img width="593" alt="Screenshot 2024-12-04 at 9 32 44 AM" src="https://github.com/user-attachments/assets/ea21cee7-5308-429c-99b9-b81e39a495ca">

**Comment by jepes1981** [comment]
I was able to hide elements relating to semitones, but the placeholder is still there. If I try to set the element display to `none` instead of just hiding it,  the now playing breaks because it is trying to access elements that are no longer in the page. 

![image](https://github.com/user-attachments/assets/ad0b1096-061a-432e-9a98-481a178bddaa)

Under the now playing statement in home.html:
```
          if (obj.is_ffmpeg_librubberband) {
            librubberband = obj.is_ffmpeg_librubberband;
            console.log("librubberband and obj.is_ffmpeg_librubberband: ", librubberband, obj.is_ffmpeg_librubberband);
          }

          console.log("librubberband value: ", librubberband);
          if (librubberband != true) {
            console.log("librubberband != true : ", librubberband != true);
            var semitoneui_0 = document.getElementById("semitone-ui-0");
            var semitoneui_1 = document.getElementById("semitone-ui-1");
            var semitoneui_2 = document.getElementById("semitone-ui-2");
            var semitomes_info = document.getElementById("semitones-info");
            //semitomes_info.style.display = 'none';
            //output.style.display = 'none';
            //semitoneui_1.style.display = 'none';
            //semitoneui_2.style.display = 'none';
            //semitoneui_0.style.display = 'none';
            //semitomes_info.style.display = 'none';
            //output.style.display = 'none';
            //semitoneui_1.style.display = 'none';
            semitoneui_2.style.visibility = 'hidden';
            semitoneui_0.style.visibility = 'hidden';

          }
```


*** Only basic knowledge in all language involved, just trying to learn actually.

**Comment by vicwomg** [comment]
You should use the flask template to hide the element. 

Under app.py, modify this block:

```python
@app.route("/")
def home():
    return render_template(
        "home.html",
        site_title=site_name,
        title="Home",
        transpose_value=k.now_playing_transpose,
        admin=is_admin(),
    )
```

You should add a new variable for `enable_transpose` which will essentially check for lib rubberband on the backend (however you are doing that, I'd suggest adding a new field to the k. object called is_transpose_enabled that makes this calculation)

```python
@app.route("/")
def home():
    return render_template(
        "home.html",
        site_title=site_name,
        title="Home",
        transpose_value=k.now_playing_transpose,
        admin=is_admin(),
        enable_transpose=k.is_transpose_enabled. 
    )
```

Next, modify the home.html template, and enclose the block of html for the transposition elements in an template if block:

```
{% if enable_transpose %}
  <div class="is-flex" style="justify-content: space-between">
    <div>
      {# MSG: Title of a control to change the key/pitch of the playing song. #}
      <h4>{% trans %}Change Key{% endtrans %}</h4>
    </div>
    <div class="is-flex">
      <h4 id="semitones-label"></h4>
      <a id="semitones-info">
        <i class="icon icon-info-circled-1" title="Info"></i
      ></a>
    </div>
  </div>
{% endif %}

Hope that makes sense
