### ISSUE TITLE
Pitch change possibilities?

### ISSUE THREAD

**Issue by Hartebee5t** [vicwomg/pikaraoke#50]
Now that VLC is available as the player, pitch change becomes feasible.

I haven't got the Python skills to implement it in code, but I've discovered that the VLC command-line provides for pitch-change using the option sequence
` --audio-filter=scaletempo_pitch --pitch-shift=n `
where 'n' is the signed number of semitones of transpose to be applied to the audio track. It has a range of -12 to +12 (+/- 1 octave).

VLC does throw some errors when running it from the CLI but it still plays the chosen mp4 with the pitch-change applied.  

I have to say it sounds disappointingly 'warbly' but there are some filter config parameters that _might_ provide some adjustment to improve this (I haven't tried to experiment with them yet). These are to be found in the [scaletempo_pitch] section of the file ~/.config/vlc/vlcrc 
The parameters provided are Stride Length, Overlap Length, Search Length and Pitch Shift. I notice that in the file Pitch Shift is a float, but at the command line it seems that VLC only accepts certain multiples of 0.1
There's some explanation of these terms [here](https://wiki.videolan.org/VLC-2-1-x_command-line_help/) (search for scaletempo)

**Comment by vicwomg** [comment]
This is great. Thanks for hunting down those CLI options. Yes the quality is not super great, but that might be the nature of real-time processing. 

I read that this improves the quality a bit:
`--speex-resampler-quality 10 --src-converter-type 0`

It sounds decent to my ears, at least on OS X. Not sure if this is also processor-bound

**Comment by vicwomg** [comment]
Prototype of this is working on branch https://github.com/vicwomg/pikaraoke/compare/50-pitch-change . I'd appreciate some external testing and feedback. Only appears when using --use-vlc option

<img width="354" alt="Screen Shot 2020-09-23 at 11 25 13 AM" src="https://user-images.githubusercontent.com/4107190/94053787-a34b6780-fd8f-11ea-8679-7e0a3276d8dc.png">

Initial tests seem to show that the pi 4 leaves much to be desired in terms of audio quality. But oddly, it sounds pretty OK on my OS X machine. Makes me wonder if this is a hardware issue. 

I believe the "Stride Length, Overlap Length, Search Length" parameters are auto set based on the bitrate of the file. I have no idea what they do, but I'm guessing that messing with them will make things worse. If anyone has the bandwidth to experiment it would be much appreciated.

**Comment by vicwomg** [comment]
Ok, checked on my pi3 and the sound was _horrible_, looked at the CPU usage and it was spiking at 100%. I think this audio filter is CPU bound. Might be able to sound less bad by adjusting these values for slower processors:

--speex-resampler-quality 10 --src-converter-type 0

Not expecting miracles though.

Sounds fine on windows and OS X though where CPUs are not as stretched

**Comment by Hartebee5t** [comment]
I like the track you chose as the test clip for your screenshot!  Big HL&TN fan.

I'm still a git-noob, so not sure how to try out the latest branch build. Do I need to fetch and merge my own local repository? Does it git only allow me to clone the master rather than a branch?

**Comment by vicwomg** [comment]
> I like the track you chose as the test clip for your screenshot! Big HL&TN fan.

Thanks for not judging me on the next track, it's kind of an inside joke around here 😂

> I'm still a git-noob, so not sure how to try out the latest branch build. Do I need to fetch and merge my own local repository? Does git only allow me to clone the master rather than a branch?

`git checkout master; git pull` (grabs all the branches from master)

```git checkout 50-pitch-change 
git pull``` (checks out this branch)

Then to switch back
`git checkout master`

> I was reluctant to stray from the clone path as I wasn't sure it wouldn't mess up your repository history in the process.

**Comment by vicwomg** [comment]
Latest version addresses the stuttering on pi, sound quality suffers in lower bass frequency, but it's adequate. I'm not certain any other real-time pitch shifting effects that could fare much better.

May move this to the develop branch tonight

**Comment by Hartebee5t** [comment]
Thanks vicwomg.
I'm not sure if it was due to overlapping VLCs (I don't think so) but one thing I'd noticed when trying the transpose feature is that, once a pitch-change has been activated, if a different page is viewed on the controlling device (say, to Search or Browse for another track) and then the app is returned to the Home page, the pitch-change slider display resets to indicate 0 pitch-shift, even though the track is playing with a non-zero pitch-shift in force.

**Comment by vicwomg** [comment]
Thanks for reporting that, I added the current transposition value under the Now Playing song title. The control itself will always reset to 0 after submission, a little too many weird corner cases to try to store the value there and also have it be the input.

**Comment by Hartebee5t** [comment]
That latest commit definitely handles the pitch-change better, and the slider state solution works well.
Thanks

**Comment by vicwomg** [comment]
Merged to master

**Comment by twizzlenaut** [comment]
I'm new to the world of Raspberry Pi and programming in general, so please forgive my ignorance -

I'm noticing quite a bit of 'warbling' - as Hartebee5t put it - when using pitch shifting on the Raspberry Pi 3. Is there anyway to optimize processing to improve quality/smooth out the audio? I've tried playing around with `speex_quality` and `src_type` in vlcclient.py to no avail. I am considering overclocking to see if that helps at all.

Also, does the speex codec being originally designed for human speech affect this? I saw that [this page](https://wiki.videolan.org/Speex/) mentions that the codec may perform poorly with non-human frequencies.

**Comment by vicwomg** [comment]
I think you’re pretty much spot on. Unless there’s another algorithm
available to VLC there may not be room for improvements.

I will say that I am currently working on porting the playback system off
of vlc and in to ffmpeg. I’ve got pitch shift working using the rubberband
algorithm and it sounds great to my ears.

-v
