### ISSUE TITLE
cherrypy

### ISSUE THREAD

**Issue by pablocamana** [vicwomg/pikaraoke#55]
Hi there, 

When trying to launch the app, I'm getting the following error. Any thoughts here? Also, does the youtube-dl issue impact the program working completely or just is that for downloading songs in advance or something? 

Traceback (most recent call last):
  File "app.py", line 9, in <module>
    import cherrypy
ImportError: No module named 'cherrypy'

**Comment by vicwomg** [comment]
Sounds like you have not installed all the required libraries. Did you run setup-pi.sh? If so, what's the output?

And yes, there is heavy dependency on YouTube-dl which sort of puts this project in limbo at the moment.

**Comment by pablocamana** [comment]
Yeah -- I'm starting over with the install, hoping that clears any issues. Re: YouTube-dl... Seems its popping back up in other places... possible to use these instead? https://thenextweb.com/dd/2020/10/27/github-took-down-youtube-dl-so-devs-made-more-copies/

**Comment by vicwomg** [comment]
The issue isn't with downloading YouTube-dl, the issue is whether or not it will be updated in the future. There is currently a bug in searching #54

**Comment by pablocamana** [comment]
Ah got it -- so there is a bug independent of the DCMA issue. Thanks, got the Cherrypy issue resolved with a clean install. Was so excited to use this this weekend :(

**Comment by vicwomg** [comment]
yeah it's a bummer, but there might be some workarounds see #54 for updates
