### ISSUE TITLE
Allow searching/downloading by YouTube URL

### ISSUE THREAD

**Issue by vicwomg** [vicwomg/pikaraoke#59]
Good suggestion here:
https://github.com/vicwomg/pikaraoke/issues/54#issuecomment-718068838

If there is an issue searching for a specific track, a user should be able to override the default search by pasting a YouTube URL directly into the search field and download it. This url can be obtained from a browser or the Youtube app.

Considerations:
- How to reliably detect a YouTube url? (mobile variants, query strings, case sensitivity)
- How to make this clear in the UI? Minimal verbiage below the search input? Already pretty wordy there. Changing the button text to "download" if a url is detected?

**Comment by vicwomg** [comment]
Youtube links from various sources:
- https://youtu.be/< video_id >
- https://www.youtube.com/watch?v=<video_id>

More: 
https://gist.github.com/Glurt/ea11b690ba4b1…

**Comment by EdFabre** [comment]
Looks like a fun one. I have been swamped with work so prolly can't take a crack anytime soon
