### ISSUE TITLE
Allow search for non-"karaoke" results

### ISSUE THREAD

**Issue by vicwomg** [vicwomg/pikaraoke#60]
The search method forces "karaoke" at the end of the search string to return karaoke results. This works most of the time, but may be too limiting, as some karaoke results could show under "lyrics" "instrumental" or "raw". We should allow some way to disable the "karaoke" string and just allow a basic plain text search. 

Perhaps a checkbox under the search input "include non-karaoke matches" and a new search mode, like an optional parameter on the search method karaokeOnly=true.

**Comment by Hartebee5t** [comment]
I’ve noticed a recent change in search results where I’m getting videos of, um, let’s call them “fellow karaoke enthusiasts” performing the song being searched for, in among results featuring the karaoke track itself. Prior to about two weeks ago I don’t recall ever having got even one of those ‘performing’ videos in a search from PiKaraoke. Had something changed in the way searches were implemented in that timeframe, is it maybe something shifting at the YT end, or have I [subconsciously] started to search for really obscure tracks?  
(I’m pretty sure the last one is only for comic effect...)

**Comment by vicwomg** [comment]
Hm, can't say I've noticed that and nothing has changed with regards to how search works, which is essentially just tacking "karaoke" to the end of your search strings.

Let me know if you have a specific example (that you're willing to share :) ) and I can check to see if something is amiss

**Comment by Hartebee5t** [comment]
I’ll check the logs ...
