### ISSUE TITLE
pi: change default download directory to ~/pikaraoke/songs

### ISSUE THREAD

**Issue by vicwomg** [vicwomg/pikaraoke#61]
In desktop mode, where I suspect the majority of pi users are running this from, sudo is actually not necessary because it has a window server. Sudo is necessary running from a non-desktop CLI because it needs access to the hw screen buffer. 

Thus, the only real thing preventing non-sudo operation is that the default download directory is /usr/lib/pikaraoke/songs
If we change this to ~/pikaraoke/songs then it should allow folks to run non-sudo.

Previous users who already have the old dl directory may experience songs "disappearing" after update though. To handle this there should be some detection for this older directory and throw a warning log on launch that they either need to launch with the -d  /usr/lib/pikaraoke/songs or move their songs over to ~/pikaraoke/songs

**Comment by Hartebee5t** [comment]
While considering this change, would it be a useful point to consider alongside it if there’s a way to sub-divide the songs directory to contain sub-directories, navigable from the Browse menu within the app?
This would make browsing larger (>200 songs) libraries faster and easier, either by splitting it, say, into categories or by alphabet segment (examples only - I‘d assume sub-division would be by user choice).
Is this something I should raise as a separate issue?

**Comment by vicwomg** [comment]
This ticket's main goal is to relax the sudo dependency.

I'd say subdirectory support should be a new issue. There are a lot of things to consider there, such as whether we'd want front end UI support for creating them and moving files around, which sounds like a lot. This is the sort of thing that makes me wish I had built this in React where there are libraries abound for such things.

**Comment by vicwomg** [comment]
actually, going with ~/pikaraoke-songs/

Just in case someone blows away their ~/pikaraoke on accident to reclone or something, don't want to wipe their songs out.

**Comment by guix77** [comment]
Just did the manual install on Raspberry yesterday and it still complained about permission for /usr/lib/pikaraoke/songs. Are you sure this is committed on master ?

**Comment by vicwomg** [comment]
Sorry, this change was reverted for reasons I can't recall specifically,
but I believe it was causing problems with auto launch and the
self-contained pikaraoke image. You can still manually specify a non-root
directory using the "-d" option.

-v

**Comment by guix77** [comment]
No problem, that's already what I did and the situation is now clarified. Thanks :)
