### ISSUE TITLE
Youtube-dl path not found Lubuntu

### ISSUE THREAD

**Issue by doobiebrownies** [vicwomg/pikaraoke#65]
Trying to install on Lubuntu and followed all the instructions and installed all dependencies. When run the program I get the message:

Youtube-dl path not found! /usr/local/bin/youtube-dl

I have tried manually creating the folder but still didn't fix the issue

**Comment by vicwomg** [comment]
type "which youtube-dl"

that should tell you where YouTube-dl is installed. Take that path and pass it to the pikaraoke app.py with: "--youtubedl-path <YOUR_YOUTUBEDL_PATH>"  

if "which youtube-dl" doesn't return anything it would seem that you don't have YouTube-dl installed. Install it using whichever method is recommended by YouTube-dl's web site

**Comment by doobiebrownies** [comment]
That did the trick but now came across anther error. When running the app I'm getting errors related to port 5000

File "/<PATH>/<USERNAME>/.local/lib/python3.6/site-packages/portend.py", line 85, in_connect raise PortNotFree(tmpl.format(**locals()))
portend.PortNotFree: Port 0.0.0.0 is in use on 5000

File "/<PATH>/<USERNAME>/.local/lib/python3.6/site-packages/portend.py", line 119, in free raise Timeout("Port {port} not free on {host}.".format(**locals()))
portend.Timeout Port 5000 is not free on 0.0.0.0

cherrypy.process.wspbus.ChannelFailures: Timeout ('Port 5000 not free on 0.0.0.0'

When running on my other install on the RPI, I don't get any similar errors

**Comment by vicwomg** [comment]
The error sounds like exactly what it says, port 5000 is being used by another process.

You can either run pikaraoke on another port (using the command line option like: "--port 5001" , or pick another unused port)

If you want to find out what's using your port 5000 you can run:
lsof -i :5000

Which will show you the command and process using it. If it's unimportant you can kill/disable that process and run on default port 5000.

**Comment by doobiebrownies** [comment]
So basically "--youtubedl-path <YOUR_YOUTUBEDL_PATH>  --port 5001" ? Sorry for the multiple noob questions as this install has become more complex for me than the RPI install.

I did try to see what process was using  port 5000 but didn't find any using netstat -tulpn. I do not get anything back when I use lsof -i :5000 . After that, I tried running the app again (without --port 5001) and the app did load with a new problem. The app is broadcasting from the 127 ip range vs the 192 that's needed.

**Comment by Hartebee5t** [comment]
I'm not familiar with Lubuntu, but could troubles with ports and IP address assignments perhaps be a firewall settings issue?

**Comment by vicwomg** [comment]
My guess is your port 5000 was in use from a previous zombie'd run of pikaraoke. If it works after a reboot, then you're probably safe with the defaults and don't need to override the port.

As for the IP thing, now that sounds like an actual bug when running in certain distros of linux. Pikaraoke determines the IP via python libraries: 
gethostbyname(gethostname())

But in some situations that might return 127.0.0.1 due to hosts file/dns configuration and render that in the QR code instead of the actual DHCP IP address. You can probably connect to it on your phone if you manually type in the IP address (ex: http://<IP>:5000) into a browser.

Investigating a better way to detect IP, but this seems like it should be filed as a separate issue

**Comment by doobiebrownies** [comment]
That was my thought as well as I was trying to investigate on the RPI any differences as well. Sorry issue deviated from original report. As noted above I commented out the IPs in the hostfile and it worked. 

I'll file a separate issue for the IP detection.

**Comment by vicwomg** [comment]
thanks for the report!
