### ISSUE TITLE
QR Code rendering Hostfile/dns vs DHCP IP

### ISSUE THREAD

**Issue by doobiebrownies** [vicwomg/pikaraoke#67]
Opened from #65 

Running app renders hostfile/dns IP in QR code rather than DHCP IP. Current workaround is to comment out IP information from hostfile

Edit: Specifically, on Lubuntu Linux distro

**Comment by vicwomg** [comment]
I added a different IP detection routine. It's in the develop branch, if you want to see if that fixes this issue:

```
cd <your pikaraoke dir>
git pull
git checkout develop
git pull
```

**Comment by doobiebrownies** [comment]
Pretty sure I'm doing something wrong. I getting this message after git checkout develop : 

error: pathspec 'develop' did not match any file(s) known to git

**Comment by vicwomg** [comment]
My mistake, try this:

 "git checkout development"

**Comment by doobiebrownies** [comment]
Got this for "git checkout development"

Branch 'development' set up to track remote branch 'development' from 'origin'.
Switched to a new branch 'development'

for "git pull"

Already up to date.

Update the host file to remove comment out on 127 IPs. Ran the app and the QR code rendered the correct IP.

**Comment by vicwomg** [comment]
Excellent, thanks for checking. Confirmed this new IP detection routine works on pi, OS X, and windows. I have merged it to master. You can switch back to your master branch, do a fresh pull, and the fix should be there.

```
git checkout master
git pull
```
