### ISSUE TITLE
Add MP3 / CDG file support

### ISSUE THREAD

**Issue by BeansIsFat** [vicwomg/pikaraoke#69]
I have a CDG library and would like the ability to incorporate those files into the pikaraoke library. Is there any chance you could add CDG support? I know VLC has some support for the format although it requires selecting both the mp3 and CDG files simultaneously then playing. There's also [libCDG](https://github.com/OpenKJ/OpenKJ/tree/master/OpenKJ/libCDG) in the OpenKJ project that is quite a bit more sophisticated.

**Comment by Hartebee5t** [comment]
I like the sound of what you're looking for here, but it might be something for a side-project, like a library-conversion feature perhaps.  
It might dovetail with something I was looking into to expand the loaded library with some kind of navigable folder structure.

**Comment by vicwomg** [comment]
I actually really wanted to experiment with this at some point, but I couldn't even find a cdg file to test with! So let me know if you have a resource there.

**Comment by scottackerson** [comment]
CDG would be a very, very welcome addition here.  If you need a CDG file, there are plenty of files and/or tutorials on the internet.  Here's to hoping that we can get this supported.

**Comment by BeansIsFat** [comment]
> I actually really wanted to experiment with this at some point, but I couldn't even find a cdg file to test with! So let me know if you have a resource there.

The Internet Archive has a number of karaoke packs. Here's one with quite a few songs.
[https://archive.org/download/KaraokeVocalStarsPartyHits](https://archive.org/download/KaraokeVocalStarsPartyHits)

**Comment by BeansIsFat** [comment]
> I like the sound of what you're looking for here, but it might be something for a side-project, like a library-conversion feature perhaps.

The OpenKJ Tools project has a library conversion feature that will take MP3+CDG files and create MP4 videos. I've tried it briefly and it seems to work but I would prefer to use the MP3+CDG files directly.

**Comment by vicwomg** [comment]
@BeansIsFat thanks so much for actually providing a link to cdg files and not just telling me to google it like the last guy 😂 (fwiw I DID google it. I just got sketchy commercial karaoke sites that I didn't want to deal with). Amazing resource, archive.org has everything.

So a bit of research does reveal that it is possible to play cdg natively in VLC, but getting the mp3 audio to also play is the tricky bit. But turns out, you can do it by passing the audio file as an --input-slave

`vlc <file>.cdg --input-slave=<file>.mp3`

I'll have to try on the various platforms, but it's very promising indeed.

**Comment by BeansIsFat** [comment]
@vicwomg That's great news. On a related note, it's common for the MP3 and CDG files to be zipped. Not sure if VLC would be able to play those directly but that would be even better. According to OpenKJ Tools, the standard DEFLATE compression is the correct one to use when creating the zip files, fwiw.

**Comment by scottackerson** [comment]
> So a bit of research does reveal that it is possible to play cdg natively in VLC, but getting the mp3 audio to also play is the tricky bit. But turns out, you can do it by passing the audio file as an --input-slave

If you play the mp3, VLC will automatically play the CDG file and not require using input-slave.

**Comment by scottackerson** [comment]
I ran a quick test and the project does support CDG as is by forcing/using VLC, although it is a bit cumbersome at the moment.  By putting both CDG and MP3 files in the songs directory they are browsable and searchable.  The files are duplicated and an enhancement to remove CDG from the get_available_songs def will complete the user experience.

![IMG_9ACA75400B75-1](https://user-images.githubusercontent.com/285904/102949693-7aba3300-448e-11eb-92e8-6a9aeb91fb85.jpeg)

**Comment by vicwomg** [comment]
Good to know. 

Yes, we'll need to do some kind of filtering for allowed file extensions from the directory listing. But the other considerations would be checking to make sure there is a matching cdg file to go with the mp3, and zip file support would be a bit more involved. I suspect I'd unzip the to a temp directory shortly before playing.

**Comment by BeansIsFat** [comment]
Would it be possible to use VLC's built in zip file handling?

**Comment by vicwomg** [comment]
Good call, but looks like no. VLC is rather dumb about which file it plays in the zip file. It just picks the mp3 and doesn't see the other file.

BTW, I pushed basic mp3 + cdg support to the development branch if anyone wants to have a look. Was easier than it sounded. Turns out I don't really need to worry about all the error handling. If the cdg file is missing, no big deal, it will just play the mp3 and show the splash screen, which would tell the user something is amiss

Should support renaming and deletion too.

**Comment by BeansIsFat** [comment]
Took a quick look at the development branch and the MP3+CDG support looks good. Nice job putting it together so quickly!

**Comment by vicwomg** [comment]
zipped mp3+cdg file support has been added to the dev branch. Let me know how that looks. Are there other file extensions that these zip files hide behind other than ".zip"?

**Comment by WhatWhyIT** [comment]
I'm running the following and the cdg video is not outputting just get a black screen -- 
sudo python3 app.py --adev alsa:hw:0,0 --high-quality --port 80

**Comment by vicwomg** [comment]
Mp3+g support only works for vlc. Make sure you run with the --use-vlc
parameter. Also this is only on the development branch. It has not been
released to the master branch

**Comment by vicwomg** [comment]
> So I resolved this on my own -- Not sure if it is intended however I had to add the
> --use-vlc
> to the run options - I did not see this noted in the cdg support info

I'm not quite sure which "support info" you're referring to. The readme on the development branch should already make it clear that vlc is required. Is there something else that you found inaccurate? 

Also, the next major release will likely make vlc default anyway, per #62

**Comment by WhatWhyIT** [comment]
> pport info" you're referri

In the clone directory there is a README.txt with 

"## What's new (January 2021)

- CDG file support! Also supports zipped cdg + mp3, just add the files to the root of the download directory
- Default download directories are now ~/pikaraoke-songs

"

I guess I would expect that to say vlc start option required --

**Comment by BeansIsFat** [comment]
> zipped mp3+cdg file support has been added to the dev branch. Let me know how that looks. Are there other file extensions that these zip files hide behind other than ".zip"?

That's fantastic. Will check this out and let you know how it's working. As far as I know ".zip" is the only file extension used for this.
  
> Edit: particularly could use help looking at this on Windows. Just "educated guessed" at the proper temp dir to put extracted zips for windows users.

I have a Windows machine I could try this on. Will let you know what I find.

**Comment by scottackerson** [comment]
Looks great.  

Also, you can change the project about from "Youtube-based Karaoke machine for Raspberry Pi" to something more grand.  :)
