### ISSUE TITLE
Run using guest network

### ISSUE THREAD

**Issue by doobiebrownies** [vicwomg/pikaraoke#73]
Think I'm connected to a guest network as the IP4 address is coming out as 10.x.x.x. Can the program still run or does it have to be in the home network? My phone also has the same 10.x.x.x IP but I can't connect to the GUI. I initially was trying to assign a 192.x.x.x static address but was losing internet connection.

System: Linux Mint 19.3 Xfce

If I missed a disclaimer in the instructions, I apologize in advance.

**Comment by vicwomg** [comment]
I'm not sure what is meant by "guest network". If two clients are on the same IP range from the same router, they should be able to see each other. However, there could be more exotic router setups that I'm not familiar with thta would firewall users off from each other ¯\_(ツ)_/¯ . Can you elaborate on how your network might be configured?

**Comment by doobiebrownies** [comment]
Basically I'm connecting using a different router right (not in my home) now and getting a 10.x.x.x IP range. My phone is also connected to the same router and assigned a 10.x.x.x IPv4 address. Updated the connection setting to ignore IPv6 on the machine just to isolate variables. I thought it would still work as you have described since they are on the same IP range but I can't access the GUI from my phone when using the IP address being rendered by the program. The only possibility I can think of is that I'm connecting to a guest SSID instead of the actual home LAN. Most routers allows you to set up a guest network so people can still access the internet but not necessarily communicate with devices that you assign to the hone network devices like a network storage or your Smart TV, etc.

**Comment by vicwomg** [comment]
Ah, my understanding of my guest network is that it's just a separate range of IPs that can't access the private base range. But I guess it's possible it would lock down inter-connections too. I'll search around and see if this is common.

**Comment by doobiebrownies** [comment]
Investigated further and managed to connect directly to the router and gave me a 10.x.x.x IP as well so we can probably scratch the "guest network" limitations. It can be that LAN sharing is disabled or it can be a different issue all together.

**Comment by vicwomg** [comment]
What IP is the pikaraoke reporting? If it's 10.0.0.1, that's actually the
default when running RaspiWiFiConfig and I wonder if it's conflicting. Did
you install that package to have headless wifi setup?

**Comment by doobiebrownies** [comment]
It's not rendering 10.0.0.1 and broadcasting the DHCP assigned IP based on the available IP range. I did not do anything different with the install.

**Comment by doobiebrownies** [comment]
I figured it out @vicwomg and pretty much a user error/rookie mistake. The firewall was set to deny incoming connections which normally you don't have to worry with the RPI
