### ISSUE TITLE
Unable to rescan song folder after start

### ISSUE THREAD

**Issue by WhatWhyIT** [vicwomg/pikaraoke#77]
I've been adding song files from various sources while the system is running.
The browse song list does not update when songs are added directly to the filepath.

Add an option to rescan the songs directory from the info page.

**Comment by vicwomg** [comment]
Good idea. Probably something we'll start to see more of with folks adding cdg files manually.

**Comment by Hartebee5t** [comment]
Could I suggest that the rescan option be extended a little to permit a (limited) change in folder? 
As a constraint on scope-creep, we could limit the folder range to an adjacent folder (or maybe a sub-folder, instead?) to the one nominated in the launch command string. This would allow some simple categorising of songs within the library.
