### ISSUE TITLE
Add overlay for VLC

### ISSUE THREAD

**Issue by BeansIsFat** [vicwomg/pikaraoke#80]
I've been experimenting with the VLC command line and think I've found a way to get the overlay working. It uses the [marquee and logo subpicture filters](https://wiki.videolan.org/Documentation:Command_line/#Subpictures_Filters) chained together.

Here's the basic structure of the argument. The documentation for VLC shows it with an escaped string.

```'--sub-source=logo{file=qrcode.png,x=20,y=20,opacity=200}:marq{marquee="Connect at: http://192.168.86.247:5000",x=130,y=20,color=0xFFFFFF,size=24,opacity=200}'```

There's not a way to resize the QR code image so that would have to be addressed. I manually resized qrcode.png to 100x100 for my tests and that seemed to be a good size.

An additional marquee filter could be added to show the upcoming song along the bottom of the screen if that's a desirable feature. It looks like they need to be chained to gether in a single `--sub-source` argument, not separate arguments, FYI.

**Comment by WhatWhyIT** [comment]
As a feature for the QR code resizing -- 
Start load option to specify the QR code size - Or maybe a way to pick the size dynamically from the admin page?

**Comment by vicwomg** [comment]
Great info thanks! 

If you want to take a crack at it, I think you can just have the python qrcode library spit out 2 files, one regular size and one smaller (e.g. qrcode-100x100.png) and then use the smaller one for the overlay.

**Comment by vicwomg** [comment]
--add-overlay QR code support has been added to the development branch. Let me know if you have any feedback
