### ISSUE TITLE
Queue should not refresh whole page on a timer

### ISSUE THREAD

**Issue by vicwomg** [vicwomg/pikaraoke#91]
The queue page refreshes on a timer to keep up to date. This is overkill and leads to the page flashing periodically. 

There should be an API that returns the current queue refetched on an interval, and only repaint if there has been a change to the currently displayed queue.

**Comment by WhatWhyIT** [comment]
> The queue page refreshes on a timer to keep up to date. This is overkill and leads to the page flashing periodically.
> 
> There should be an API that returns the current queue refetched on an interval, and only repaint if there has been a change to the currently displayed queue.

Just saying... It's very nice to see you notice optimization opportunities within  you're own app work to resolve them.
