### ISSUE TITLE
Image credentials not listed

### ISSUE THREAD

**Issue by mbreughe** [vicwomg/pikaraoke#94]
I attempted running straight from the image provided. However, the credentials are not the default raspberry credentials (i.e., username: pi, password: raspberry). Please list the credentials in the README or on the download page. Thank you!

**Comment by vicwomg** [comment]
my apologies. I forgot about that. Will add to the readme but in case you haven't guessed it already, the password is "pikaraoke"

**Comment by mbreughe** [comment]
Thanks, that worked!
