### ISSUE TITLE
Update tag-line description displayed to Github

### ISSUE THREAD

**Issue by Hartebee5t** [vicwomg/pikaraoke#97]
Now that the project can run under more general Linux, Windows or OSX platforms, beyond the original Pi-based concept, it's maybe time to broaden the scope of the top level summary shown to Github users briwsing/searching through projects:
"Youtube-based Karaoke machine for Raspberry Pi"

**Comment by vicwomg** [comment]
Really tricky one, but I think I managed to fix this :)
